% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  a4paper,
]{scrreport}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{5}
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{venndiagram}
\newcommand{\NN}{\mathbb{N}}
\newcommand{\ZZ}{\mathbb{Z}}
\newcommand{\QQ}{\mathbb{Q}}
\newcommand{\RR}{\mathbb{R}}
\newcommand{\CC}{\mathbb{C}}
\DeclareMathOperator{\operatorname{Int}}{Int}
\DeclareMathOperator{\operatorname{Ext}}{Ext}
\DeclareMathOperator{\operatorname{Fr}}{Fr}
\DeclareMathOperator{\Adh}{Adh}
\DeclareMathOperator{\Ac}{Ac}
\DeclareMathOperator{\sen}{sen}
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[many]{tcolorbox}}
\@ifpackageloaded{fontawesome5}{}{\usepackage{fontawesome5}}
\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{acacac}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582ec}
\definecolor{quarto-callout-important-color-frame}{HTML}{d9534f}
\definecolor{quarto-callout-warning-color-frame}{HTML}{f0ad4e}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02b875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{fd7e14}
\makeatother
\makeatletter
\@ifpackageloaded{tikz}{}{\usepackage{tikz}}
\makeatother
\makeatletter
\@ifpackageloaded{bookmark}{}{\usepackage{bookmark}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Tabla de contenidos}
\else
  \newcommand\contentsname{Tabla de contenidos}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{Listado de Figuras}
\else
  \newcommand\listfigurename{Listado de Figuras}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{Listado de Tablas}
\else
  \newcommand\listtablename{Listado de Tablas}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figura}
\else
  \newcommand\figurename{Figura}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Tabla}
\else
  \newcommand\tablename{Tabla}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listado}
\newcommand*\listoflistings{\listof{codelisting}{Listado de Listados}}
\usepackage{amsthm}
\theoremstyle{definition}
\newtheorem{exercise}{Ejercicio}[chapter]
\theoremstyle{remark}
\renewcommand*{\proofname}{Prueba}
\newtheorem*{remark}{Observación}
\newtheorem*{solution}{Solución}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[many]{tcolorbox}}
\makeatother
\makeatletter
\@ifundefined{shadecolor}{\definecolor{shadecolor}{rgb}{.97, .97, .97}}
\makeatother
\makeatletter
\makeatother
\ifLuaTeX
\usepackage[bidi=basic]{babel}
\else
\usepackage[bidi=default]{babel}
\fi
\babelprovide[main,import]{spanish}
% get rid of language-specific shorthands (see #6817):
\let\LanguageShortHands\languageshorthands
\def\languageshorthands#1{}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Pácticas de Análisis Matemático con Julia},
  pdfauthor={Alfredo Sánchez Alberca},
  pdflang={es},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Pácticas de Análisis Matemático con Julia}
\author{Alfredo Sánchez Alberca}
\date{6/1/22}

\begin{document}
\begin{titlepage}

%\AddToShipoutPicture*{\put(0,0){\includegraphics[scale=0.8]{img/background2}}} % Imagen de fondo, requiere el paquete eso-pic.
\begin{center}
\vspace*{5cm}

\Huge
{\textbf{\textsf{Pácticas de Análisis Matemático con Julia}}}

\vspace{0.5cm}
\LARGE
{\textbf{\textsf{}}}

\vspace{1.5cm}

\includegraphics[width=0.4\textwidth]{img/logos/infinito-julia.png}
\end{center}

\vfill

\begin{flushleft}
\begin{tabular}{ll}
\includegraphics[width=0.1\textwidth]{img/logos/aprendeconalf.png} & \parbox[b]{5cm}{\Large\textsf{Alfredo
Sánchez
Alberca}\\ \textsf{asalber@ceu.es} \\ \textsf{https://aprendeconalf.es}}
\end{tabular}
\end{flushleft}
\end{titlepage}\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[borderline west={3pt}{0pt}{shadecolor}, sharp corners, enhanced, frame hidden, boxrule=0pt, breakable, interior hidden]}{\end{tcolorbox}}\fi

\renewcommand*\contentsname{Tabla de contenidos}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}
\bookmarksetup{startatroot}

\hypertarget{prefacio}{%
\chapter*{Prefacio}\label{prefacio}}
\addcontentsline{toc}{chapter}{Prefacio}

\markboth{Prefacio}{Prefacio}

¡Bienvenido a Prácticas de Análisis Matemático con Julia!

Este libro presenta una recopilación de prácticas de Análisis Matemático
en una y varias variables reales con el lenguaje de programación
\href{https://julialang.org/}{Julia}, con problemas aplicados a las
Ciencias y las Ingenierías.

No es un libro para aprender a programar con Julia, ya que solo enseña
el uso del lenguaje y de algunos de sus paquetes para resolver problemas
de Cálculo tanto numérico como simbólico. Para quienes estén interesados
en aprender a programar en este Julia, os recomiendo leer este
\href{https://aprendeconalf.es/manual-julia/}{manual de Julia}.

\hypertarget{licencia}{%
\section*{Licencia}\label{licencia}}
\addcontentsline{toc}{section}{Licencia}

\markright{Licencia}

Esta obra está bajo una licencia Reconocimiento -- No comercial --
Compartir bajo la misma licencia 3.0 España de Creative Commons. Para
ver una copia de esta licencia, visite
\url{https://creativecommons.org/licenses/by-nc-sa/3.0/es/}.

Con esta licencia eres libre de:

\begin{itemize}
\tightlist
\item
  Copiar, distribuir y mostrar este trabajo.
\item
  Realizar modificaciones de este trabajo.
\end{itemize}

Bajo las siguientes condiciones:

\begin{itemize}
\item
  \textbf{Reconocimiento}. Debe reconocer los créditos de la obra de la
  manera especificada por el autor o el licenciador (pero no de una
  manera que sugiera que tiene su apoyo o apoyan el uso que hace de su
  obra).
\item
  \textbf{No comercial}. No puede utilizar esta obra para fines
  comerciales.
\item
  \textbf{Compartir bajo la misma licencia}. Si altera o transforma esta
  obra, o genera una obra derivada, sólo puede distribuir la obra
  generada bajo una licencia idéntica a ésta.
\end{itemize}

Al reutilizar o distribuir la obra, tiene que dejar bien claro los
términos de la licencia de esta obra.

Estas condiciones pueden no aplicarse si se obtiene el permiso del
titular de los derechos de autor.

Nada en esta licencia menoscaba o restringe los derechos morales del
autor.

\bookmarksetup{startatroot}

\hypertarget{introducciuxf3n}{%
\chapter{Introducción}\label{introducciuxf3n}}

La gran potencia de cálculo alcanzada por los ordenadores en las últimas
décadas ha convertido a los mismos en poderosas herramientas al servicio
de todas aquellas disciplinas que, como las matemáticas, requieren
cálculos largos y complejos.

\href{https://julialang.org/}{Julia} es un lenguaje de programación
especialmente orientado al cálculo numérico y el análisis de datos.
Julia permite además realizar cálculos simbólicos y dispone de una gran
\href{https://julialang.org/packages/}{biblioteca de paquetes} con
aplicaciones en muy diversas áreas de las Matemáticas como Cálculo,
Álgebra, Geometría, Matemática Discreta o Estadística.

\includegraphics{./img/logos/logo-julia.png}

La ventaja de Julia frente a otros programas habituales de cálculo como
Mathematica, MATLAB o Sage radica en su potencia de cálculo y su
velocidad (equiparable al lenguaje C), lo que lo hace ideal para manejar
grandes volúmenes de datos o realizar tareas que requieran largos y
complejos cálculos. Además, es software libre por lo que resulta ideal
para introducirlo en el aula como soporte computacional para los modelos
matemáticos sin coste alguno.

En el siguiente enlace se explica el procedimiento de
\href{https://aprendeconalf.es/manual-julia/intro.html\#instalaci\%C3\%B3n-de-julia}{instalación
de Julia}.

Existen también varios entornos de desarrollo online que permiten
ejecutar código en Julia sin necesidad de instalarlo en nuestro
ordenador, como por ejemplo
\href{https://replit.com/languages/julia}{Replit},
\href{https://cocalc.com/}{Cocalc} o
\href{https://codeanywhere.com/languages/julia}{Codeanywhere}.

El objetivo de esta práctica es introducir al alumno en la utilización
de este lenguaje, enseñándole a realizar las operaciones básicas más
habituales en Cálculo.

\hypertarget{el-repl-de-julia}{%
\section{El REPL de Julia}\label{el-repl-de-julia}}

Para arrancar el REPL\^{}(REPL es el acrónimo de Read, Evaluate, Print
and Loop, que describe el funcionamiento del compilador de Julia) de
julia basta con abrir una terminal y teclear \texttt{julia}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prompt}\OperatorTok{\textgreater{}}\NormalTok{ julia}
\NormalTok{               \_}
\NormalTok{   \_       \_ }\FunctionTok{\_}\NormalTok{(\_)\_     }\OperatorTok{|}\NormalTok{  Documentation}\OperatorTok{:}\NormalTok{ https}\OperatorTok{://}\NormalTok{docs.julialang.org}
\NormalTok{  (\_)     }\OperatorTok{|}\NormalTok{ (\_) (\_)    }\OperatorTok{|}
\NormalTok{   \_ \_   \_}\OperatorTok{|} \OperatorTok{|}\NormalTok{\_  \_\_ \_   }\OperatorTok{|}  \DataTypeTok{Type} \StringTok{"?"} \ControlFlowTok{for}\NormalTok{ help, }\StringTok{"]?"} \ControlFlowTok{for} \BuiltInTok{Pkg}\NormalTok{ help.}
  \OperatorTok{|} \OperatorTok{|} \OperatorTok{|} \OperatorTok{|} \OperatorTok{|} \OperatorTok{|} \OperatorTok{|/}\NormalTok{ \_}\SpecialStringTok{\textasciigrave{} |  |}
  \OperatorTok{|} \OperatorTok{|} \OperatorTok{|}\NormalTok{\_}\OperatorTok{|} \OperatorTok{|} \OperatorTok{|} \OperatorTok{|}\NormalTok{ (\_}\OperatorTok{|} \OperatorTok{|}  \OperatorTok{|}\NormalTok{  Version }\FloatTok{1.7.3}\NormalTok{ (}\FloatTok{2022}\OperatorTok{{-}}\FloatTok{05}\OperatorTok{{-}}\FloatTok{06}\NormalTok{)}
\NormalTok{ \_}\OperatorTok{/} \OperatorTok{|\textbackslash{}}\NormalTok{\_\_}\CharTok{\textquotesingle{}\_|\_|\_|\textbackslash{}\_\_\textquotesingle{}}\NormalTok{\_}\OperatorTok{|}  \OperatorTok{|}\NormalTok{  Official https}\OperatorTok{://}\NormalTok{julialang.org}\OperatorTok{/}\NormalTok{ release}
\OperatorTok{|}\NormalTok{\_\_}\OperatorTok{/}                   \OperatorTok{|}

\NormalTok{julia}\OperatorTok{\textgreater{}}
\end{Highlighting}
\end{Shaded}

\hypertarget{el-gestor-de-paquetes-de-julia}{%
\section{El gestor de paquetes de
Julia}\label{el-gestor-de-paquetes-de-julia}}

Julia viene con varios paquetes básicos preinstalados, como por ejemplo
el paquete \texttt{LinearAlgebra} que define funciones básicas del
Álgebra Lineal, pero en estas prácticas utilizaremos otros muchos
paquetes que añaden más funcionalidades que no vienen instalados por
defecto y tendremos que instalarlos aparte. Julia tiene un potente
gestor de paquetes que facilita la búsqueda, instalación, actualización
y eliminación de paquetes.

Por defecto el gestor de paquetes utiliza el
\href{https://julialang.org/packages/}{repositorio de paquetes oficial}
pero se pueden instalar paquetes de otros repositorios.

Para entrar en el modo de gestión de paquetes hay que teclear
\texttt{{]}}. Esto produce un cambio en el \emph{prompt} del REPL de
Julia.

Los comandos más habituales son:

\begin{itemize}
\tightlist
\item
  \texttt{add\ p}: Instala el paquete \texttt{p} en el entorno activo de
  Julia.
\item
  \texttt{update}: Actualiza los paquetes del entorno activo de Julia.
\item
  \texttt{status}: Muestra los paquetes instalados y sus versiones en el
  entorno activo de Julia.
\item
  \texttt{remove\ p}: Elimina el paquete \texttt{p} del entorno activo
  de Julia.
\end{itemize}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ejemplo}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Para instalar el paquete \texttt{SymPy} para cálculo simbólico basta con
teclear \texttt{add\ Sympy}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\PreprocessorTok{@v1}\FloatTok{.7}\NormalTok{) pkg}\OperatorTok{\textgreater{}}\NormalTok{ add SymPy}
\NormalTok{    Updating registry at }\SpecialStringTok{\textasciigrave{}\textasciitilde{}/.julia/registries/General.toml\textasciigrave{}}
\NormalTok{   Resolving package versions}\OperatorTok{...}
\NormalTok{    Updating }\SpecialStringTok{\textasciigrave{}\textasciitilde{}/.julia/environments/v1.7/Project.toml\textasciigrave{}}
\NormalTok{  [}\FloatTok{24249f21}\NormalTok{] }\OperatorTok{+}\NormalTok{ SymPy v1}\FloatTok{.1.6}
\NormalTok{    Updating }\SpecialStringTok{\textasciigrave{}\textasciitilde{}/.julia/environments/v1.7/Manifest.toml\textasciigrave{}}
\NormalTok{  [}\FloatTok{3709}\NormalTok{ef60] }\OperatorTok{+}\NormalTok{ CommonEq v0}\FloatTok{.2.0}
\NormalTok{  [}\FloatTok{38540f10}\NormalTok{] }\OperatorTok{+}\NormalTok{ CommonSolve v0}\FloatTok{.2.1}
\NormalTok{  [}\FloatTok{438e738}\NormalTok{f] }\OperatorTok{+}\NormalTok{ PyCall v1}\FloatTok{.93.1}
\NormalTok{  [}\FloatTok{24249f21}\NormalTok{] }\OperatorTok{+}\NormalTok{ SymPy v1}\FloatTok{.1.6}
\end{Highlighting}
\end{Shaded}

\end{tcolorbox}

\hypertarget{operadores-aritmuxe9ticos.}{%
\section{Operadores aritméticos.}\label{operadores-aritmuxe9ticos.}}

El uso más simple de Julia es la realización de operaciones aritméticas
como en una calculadora. En Julia se utilizan los siguientes operadores.

\begin{longtable}[]{@{}ll@{}}
\toprule()
Operador & Descripción \\
\midrule()
\endhead
\texttt{x\ +\ y} & Suma \\
\texttt{x\ -\ y} & Resta \\
\texttt{x\ *\ y} & Producto \\
\texttt{x\ /\ y} & División \\
\texttt{x\ ÷\ y} & Cociente división entera \\
\texttt{x\ \%\ y} & Resto división entera \\
\texttt{x\ \^{}\ y} & Potencia \\
\bottomrule()
\end{longtable}

\hypertarget{operadores-de-comparaciuxf3n}{%
\section{Operadores de comparación}\label{operadores-de-comparaciuxf3n}}

\begin{longtable}[]{@{}ll@{}}
\toprule()
Operador & Descripción \\
\midrule()
\endhead
\texttt{==} & Igualdad \\
\texttt{!=}, \texttt{≠} & Desigualdad \\
\texttt{\textless{}} & Menor que \\
\texttt{\textless{}=}, \texttt{≤} & Menor o igual que \\
\texttt{\textgreater{}} & Mayor que \\
\texttt{\textgreater{}=}, \texttt{≥} & Mayor o igual que \\
\bottomrule()
\end{longtable}

\hypertarget{operadores-booleanos}{%
\section{Operadores booleanos}\label{operadores-booleanos}}

\begin{longtable}[]{@{}ll@{}}
\toprule()
Operador & Descripción \\
\midrule()
\endhead
\texttt{!x} & Negación \\
\texttt{x\ \&\&\ y} & Conjunción (y) \\
\texttt{x\ \textbar{}\textbar{}\ y} & Disyunción (o) \\
\bottomrule()
\end{longtable}

Existen también un montón de funciones predefinidas habituales en
Cálculo.

\hypertarget{funciones-de-redondeo}{%
\section{Funciones de redondeo}\label{funciones-de-redondeo}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.4231}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.5769}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Función
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Descripción
\end{minipage} \\
\midrule()
\endhead
\texttt{round(x)} & Devuelve el entero más próximo a \texttt{x} \\
\texttt{round(x,\ digits\ =\ n)} & Devuelve al valor más próximo a
\texttt{x} con \texttt{n} decimales \\
\texttt{floor(x)} & Redondea \texttt{x} al próximo entero menor \\
\texttt{ceil(x)} & Redondea \texttt{x} al próximo entero mayor \\
\texttt{trunc(x)} & Devuelve la parte entera de \texttt{x} \\
\bottomrule()
\end{longtable}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ejemplo}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{round}\NormalTok{(}\FloatTok{2.7}\NormalTok{)}
\FloatTok{3.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{floor}\NormalTok{(}\FloatTok{2.7}\NormalTok{)}
\FloatTok{2.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{floor}\NormalTok{(}\OperatorTok{{-}}\FloatTok{2.7}\NormalTok{)}
\OperatorTok{{-}}\FloatTok{3.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{ceil}\NormalTok{(}\FloatTok{2.7}\NormalTok{)}
\FloatTok{3.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{ceil}\NormalTok{(}\OperatorTok{{-}}\FloatTok{2.7}\NormalTok{)}
\OperatorTok{{-}}\FloatTok{2.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{trunc}\NormalTok{(}\FloatTok{2.7}\NormalTok{)}
\FloatTok{2.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{trunc}\NormalTok{(}\OperatorTok{{-}}\FloatTok{2.7}\NormalTok{)}
\OperatorTok{{-}}\FloatTok{2.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{round}\NormalTok{(}\FloatTok{2.5}\NormalTok{)}
\FloatTok{2.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{round}\NormalTok{(}\FloatTok{2.786}\NormalTok{, digits }\OperatorTok{=} \FloatTok{2}\NormalTok{)}
\FloatTok{2.79}
\end{Highlighting}
\end{Shaded}

\end{tcolorbox}

\hypertarget{funciones-de-divisiuxf3n}{%
\section{Funciones de división}\label{funciones-de-divisiuxf3n}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1970}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.8030}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Función
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Descripción
\end{minipage} \\
\midrule()
\endhead
\texttt{div(x,y)}, \texttt{x÷y} & Cociente de la división entera \\
\texttt{fld(x,y)} & Cociente de la división entera redondeado hacia
abajo \\
\texttt{cld(x,y)} & Cociente de la división entera redondeado hacia
arriba \\
\texttt{rem(x,y)}, \texttt{x\%y} & Resto de la división entera. Se
cumple \texttt{x\ ==\ div(x,y)*y\ +\ rem(x,y)} \\
\texttt{mod(x,y)} & Módulo con respecto a \texttt{y}. Se cumple
\texttt{x\ ==\ fld(x,y)*y\ +\ mod(x,y)} \\
\texttt{gcd(x,y...)} & Máximo común divisor positivo de \texttt{x},
\texttt{y},\ldots{} \\
\texttt{lcm(x,y...)} & Mínimo común múltiplo positivo de \texttt{x},
\texttt{y},\ldots{} \\
\bottomrule()
\end{longtable}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ejemplo}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{div}\NormalTok{(}\FloatTok{5}\NormalTok{,}\FloatTok{3}\NormalTok{)}
\FloatTok{1}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{cld}\NormalTok{(}\FloatTok{5}\NormalTok{,}\FloatTok{3}\NormalTok{)}
\FloatTok{2}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FloatTok{5}\OperatorTok{\%}\FloatTok{3}
\FloatTok{2}

\NormalTok{julia}\OperatorTok{\textgreater{}} \OperatorTok{{-}}\FloatTok{5}\OperatorTok{\%}\FloatTok{3}
\OperatorTok{{-}}\FloatTok{2}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{mod}\NormalTok{(}\FloatTok{5}\NormalTok{,}\FloatTok{3}\NormalTok{)}
\FloatTok{2}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{mod}\NormalTok{(}\OperatorTok{{-}}\FloatTok{5}\NormalTok{,}\FloatTok{3}\NormalTok{)}
\FloatTok{1}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{gcd}\NormalTok{(}\FloatTok{12}\NormalTok{,}\FloatTok{18}\NormalTok{)}
\FloatTok{6}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{lcm}\NormalTok{(}\FloatTok{12}\NormalTok{,}\FloatTok{18}\NormalTok{)}
\FloatTok{36}
\end{Highlighting}
\end{Shaded}

\end{tcolorbox}

\hypertarget{funciones-para-el-signo-y-el-valor-absoluto}{%
\section{Funciones para el signo y el valor
absoluto}\label{funciones-para-el-signo-y-el-valor-absoluto}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2892}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.7108}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Función
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Descripción
\end{minipage} \\
\midrule()
\endhead
\texttt{abs(x)} & Valor absoluto de \texttt{x} \\
\texttt{sign(x)} & Devuelve -1 si \texttt{x} es positivo, -1 si es
negativo y 0 si es 0. \\
\bottomrule()
\end{longtable}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ejemplo}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{abs}\NormalTok{(}\FloatTok{2.5}\NormalTok{)}
\FloatTok{2.5}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{abs}\NormalTok{(}\OperatorTok{{-}}\FloatTok{2.5}\NormalTok{)}
\FloatTok{2.5}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{sign}\NormalTok{(}\OperatorTok{{-}}\FloatTok{2.5}\NormalTok{)}
\OperatorTok{{-}}\FloatTok{1.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{sign}\NormalTok{(}\FloatTok{0}\NormalTok{)}
\FloatTok{0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{sign}\NormalTok{(}\FloatTok{2.5}\NormalTok{)}
\FloatTok{1.0}
\end{Highlighting}
\end{Shaded}

\end{tcolorbox}

\hypertarget{rauxedces-exponenciales-y-logaritmos}{%
\section{Raíces, exponenciales y
logaritmos}\label{rauxedces-exponenciales-y-logaritmos}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.7500}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Función
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Descripción
\end{minipage} \\
\midrule()
\endhead
\texttt{sqrt(x)}, \texttt{√x} & Raíz cuadrada de \texttt{x} \\
\texttt{cbrt(x)}, \texttt{∛x} & Raíz cúbica de \texttt{x} \\
\texttt{exp(x)} & Exponencial de \texttt{x} \\
\texttt{log(x)} & Logaritmo neperiano de \texttt{x} \\
\texttt{log(b,x)} & Logaritmo en base \texttt{b} de \texttt{x} \\
\texttt{log2(x)} & Logaritmo en base 2 de \texttt{x} \\
\texttt{log10(x)} & Logaritmo en base 10 de \texttt{x} \\
\bottomrule()
\end{longtable}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ejemplo}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{sqrt}\NormalTok{(}\FloatTok{4}\NormalTok{)}
\FloatTok{2.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{cbrt}\NormalTok{(}\FloatTok{27}\NormalTok{)}
\FloatTok{3.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{exp}\NormalTok{(}\FloatTok{1}\NormalTok{)}
\FloatTok{2.718281828459045}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{exp}\NormalTok{(}\OperatorTok{{-}}\ConstantTok{Inf}\NormalTok{)}
\FloatTok{0.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{log}\NormalTok{(}\FloatTok{1}\NormalTok{)}
\FloatTok{0.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{log}\NormalTok{(}\FloatTok{0}\NormalTok{)}
\OperatorTok{{-}}\ConstantTok{Inf}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{log}\NormalTok{(}\OperatorTok{{-}}\FloatTok{1}\NormalTok{)}
\NormalTok{ERROR}\OperatorTok{:} \DataTypeTok{DomainError}\NormalTok{ with }\OperatorTok{{-}}\FloatTok{1.0}\OperatorTok{:}
\NormalTok{log will only }\ControlFlowTok{return}\NormalTok{ a complex result }\ControlFlowTok{if}\NormalTok{ called with a complex argument.}
\OperatorTok{...}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{log}\NormalTok{(}\OperatorTok{{-}}\FloatTok{1}\OperatorTok{+}\FloatTok{0im}\NormalTok{)}
\FloatTok{0.0} \OperatorTok{+} \FloatTok{3.141592653589793im}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{log2}\NormalTok{(}\FloatTok{2}\OperatorTok{\^{}}\FloatTok{3}\NormalTok{)}
\FloatTok{3.0}
\end{Highlighting}
\end{Shaded}

\end{tcolorbox}

\hypertarget{funciones-trigonomuxe9tricas}{%
\section{Funciones trigonométricas}\label{funciones-trigonomuxe9tricas}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.7500}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Función
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Descripción
\end{minipage} \\
\midrule()
\endhead
\texttt{hypot(x,y)} & Hipotenusa del triángulo rectángulo con catetos
\texttt{x} e \texttt{y} \\
\texttt{sin(x)} & Seno del ángulo \texttt{x} en radianes \\
\texttt{sind(x)} & Seno del ángulo \texttt{x} en grados \\
\texttt{cos(x)} & Coseno del ángulo \texttt{x} en radianes \\
\texttt{cosd(x)} & Coseno del ángulo \texttt{x} en grados \\
\texttt{tan(x)} & Tangente del ángulo \texttt{x} en radianes \\
\texttt{tand(x)} & Tangente del ángulo \texttt{x} en grados \\
\texttt{sec(x)} & Secante del ángulo \texttt{x} en radianes \\
\texttt{csc(x)} & Cosecante del ángulo \texttt{x} en radianes \\
\texttt{cot(x)} & Cotangente del ángulo \texttt{x} en radianes \\
\bottomrule()
\end{longtable}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ejemplo}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{sin}\NormalTok{(}\ConstantTok{π}\OperatorTok{/}\FloatTok{2}\NormalTok{)}
\FloatTok{1.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{cos}\NormalTok{(}\ConstantTok{π}\OperatorTok{/}\FloatTok{2}\NormalTok{)}
\FloatTok{6.123233995736766e{-}17}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{cosd}\NormalTok{(}\FloatTok{90}\NormalTok{)}
\FloatTok{0.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{tan}\NormalTok{(}\ConstantTok{π}\OperatorTok{/}\FloatTok{4}\NormalTok{)}
\FloatTok{0.9999999999999999}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{tand}\NormalTok{(}\FloatTok{45}\NormalTok{)}
\FloatTok{1.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{tan}\NormalTok{(}\ConstantTok{π}\OperatorTok{/}\FloatTok{2}\NormalTok{)}
\FloatTok{1.633123935319537e16}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{tand}\NormalTok{(}\FloatTok{90}\NormalTok{)}
\ConstantTok{Inf}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{sin}\NormalTok{(}\ConstantTok{π}\OperatorTok{/}\FloatTok{4}\NormalTok{)}\OperatorTok{\^{}}\FloatTok{2} \OperatorTok{+} \FunctionTok{cos}\NormalTok{(}\ConstantTok{π}\OperatorTok{/}\FloatTok{4}\NormalTok{)}\OperatorTok{\^{}}\FloatTok{2}
\FloatTok{1.0}
\end{Highlighting}
\end{Shaded}

\end{tcolorbox}

\hypertarget{funciones-trigonomuxe9tricas-inversas}{%
\section{Funciones trigonométricas
inversas}\label{funciones-trigonomuxe9tricas-inversas}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.7500}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Función
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Descripción
\end{minipage} \\
\midrule()
\endhead
\texttt{asin(x)} & Arcoseno (inversa del seno) de \texttt{x} en
radianes \\
\texttt{asind(x)} & Arcoseno (inversa del seno) de \texttt{x} en
grados \\
\texttt{acos(x)} & Arcocoseno (inversa del coseno) de \texttt{x} en
radianes \\
\texttt{acosd(x)} & Arcocoseno (inversa del coseno) de \texttt{x} en
grados \\
\texttt{atan(x)} & Arcotangente (inversa de la tangente) de \texttt{x}
en radianes \\
\texttt{atand(x)} & Arcotangente (inversa de la tangente) de \texttt{x}
en grados \\
\texttt{asec(x)} & Arcosecante (inversa de la secante) de \texttt{x} en
radianes \\
\texttt{acsc(x)} & Arcocosecante (inversa de la cosecante) de \texttt{x}
en radianes \\
\texttt{acot(x)} & Arcocotangente (inversa de la cotangente) de
\texttt{x} en radianes \\
\bottomrule()
\end{longtable}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ejemplo}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{asin}\NormalTok{(}\FloatTok{1}\NormalTok{)}
\FloatTok{1.5707963267948966}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{asind}\NormalTok{(}\FloatTok{1}\NormalTok{)}
\FloatTok{90.0}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{acos}\NormalTok{(}\OperatorTok{{-}}\FloatTok{1}\NormalTok{)}
\FloatTok{3.141592653589793}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{atan}\NormalTok{(}\FloatTok{1}\NormalTok{)}
\FloatTok{0.7853981633974483}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FunctionTok{atand}\NormalTok{(}\FunctionTok{tan}\NormalTok{(}\ConstantTok{π}\OperatorTok{/}\FloatTok{4}\NormalTok{))}
\FloatTok{45.0}
\end{Highlighting}
\end{Shaded}

\end{tcolorbox}

\hypertarget{precedencia-de-operadores}{%
\section{Precedencia de operadores}\label{precedencia-de-operadores}}

A la hora de evaluar una expresión aritmética, Julia evalúa los
operadores según el siguiente orden de prioridad (de mayor a menor
prioridad).

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.1071}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.7000}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.1929}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Categoría
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Operadores
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Asociatividad
\end{minipage} \\
\midrule()
\endhead
Funciones & \texttt{exp}, \texttt{log}, \texttt{sin}, etc. & \\
Exponenciación & \texttt{\^{}} & Derecha \\
Unarios & \texttt{+\ -\ √} & Derecha \\
Fracciones & \texttt{//} & Izquierda \\
Multiplicación & \texttt{*\ /\ \%\ \&\ \textbackslash{}\ ÷} &
Izquierda \\
Adición & \texttt{+\ -\ \textbar{}} & Izquierda \\
Comparaciones &
\texttt{\textgreater{}\ \textless{}\ \textgreater{}=\ \textless{}=\ ==\ !=\ !==}
& \\
Asignaciones &
\texttt{=\ +=\ -=\ *=\ /=\ //=\ \^{}=\ ÷=\ \%=\ \textbar{}=\ \&=} &
Derecha \\
\bottomrule()
\end{longtable}

Cuando se quiera evaluar un operador con menor prioridad antes que otro
con mayor prioridad, hay que utilizar paréntesis.

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ejemplo}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{julia}\OperatorTok{\textgreater{}} \FloatTok{1} \OperatorTok{+} \FloatTok{4} \OperatorTok{\^{}} \FloatTok{2} \OperatorTok{/} \FloatTok{2} \OperatorTok{{-}} \FloatTok{3}
\FloatTok{6.0}

\NormalTok{julia}\OperatorTok{\textgreater{}}\NormalTok{ (}\FloatTok{1} \OperatorTok{+} \FloatTok{4} \OperatorTok{\^{}} \FloatTok{2}\NormalTok{) }\OperatorTok{/} \FloatTok{2} \OperatorTok{{-}} \FloatTok{3}
\FloatTok{5.5}

\NormalTok{julia}\OperatorTok{\textgreater{}}\NormalTok{ (}\FloatTok{1} \OperatorTok{+} \FloatTok{4}\NormalTok{) }\OperatorTok{\^{}} \FloatTok{2} \OperatorTok{/} \FloatTok{2} \OperatorTok{{-}} \FloatTok{3}
\FloatTok{9.5}

\NormalTok{julia}\OperatorTok{\textgreater{}} \FloatTok{1} \OperatorTok{+} \FloatTok{4} \OperatorTok{\^{}} \FloatTok{2} \OperatorTok{/}\NormalTok{ (}\FloatTok{2} \OperatorTok{{-}} \FloatTok{3}\NormalTok{)}
\OperatorTok{{-}}\FloatTok{15.0}

\NormalTok{julia}\OperatorTok{\textgreater{}}\NormalTok{ (}\FloatTok{1} \OperatorTok{+} \FloatTok{4} \OperatorTok{\^{}} \FloatTok{2}\NormalTok{) }\OperatorTok{/}\NormalTok{ (}\FloatTok{2} \OperatorTok{{-}} \FloatTok{3}\NormalTok{)}
\OperatorTok{{-}}\FloatTok{17.0}
\end{Highlighting}
\end{Shaded}

\end{tcolorbox}

\hypertarget{definiciuxf3n-de-variables}{%
\section{Definición de variables}\label{definiciuxf3n-de-variables}}

Para definir variables se pueden utilizar cualquier carácter
\href{https://en.wikipedia.org/wiki/List_of_Unicode_characters}{Unicode}.
Los nombres de las variables pueden contener más de una letra y, en tal
caso, pueden usarse también números, pero siempre debe comenzar por una
letra. Así, para Julia, la expresión \texttt{xy}, no se interpreta como
el producto de la variable \(x\) por la variable \(y\), sino como la
variable \(xy\). Además, se distingue entre mayúsculas y minúsculas, así
que no es lo mismo \(xy\) que \(xY\).

\bookmarksetup{startatroot}

\hypertarget{sucesiones-de-nuxfameros-reales}{%
\chapter{Sucesiones de números
reales}\label{sucesiones-de-nuxfameros-reales}}

\hypertarget{ejercicios-resueltos}{%
\section{Ejercicios Resueltos}\label{ejercicios-resueltos}}

Para la realización de esta práctica se requieren los siguientes
paquetes:

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{SymPy  }\CommentTok{\# Para el cálculo simbólico de límites.}
\ImportTok{using} \BuiltInTok{Plots  }\CommentTok{\# Para el dibujo de gráficas.}
\CommentTok{\#plotlyjs() \# Para obtener gráficos interactivos.}
\ImportTok{using} \BuiltInTok{LaTeXStrings  }\CommentTok{\# Para usar código LaTeX en los gráficos.}
\end{Highlighting}
\end{Shaded}

\leavevmode\vadjust pre{\hypertarget{exr-sucesiones}{}}%
\begin{exercise}[]\label{exr-sucesiones}

Dar los 10 primeros términos de las siguientes sucesiones:

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  \((2n+1)_{n=1}^\infty\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Definir una función para el término general y aplicar la función a los
naturales de 1 a 10 usando
\href{https://aprendeconalf.es/manual-julia/tipos-datos-compuestos.html\#comprensi\%C3\%B3n-de-arrays}{compresiones
de arrays}.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=} \FloatTok{2}\NormalTok{n }\OperatorTok{+} \FloatTok{1}
\FunctionTok{print}\NormalTok{([}\FunctionTok{x}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[3, 5, 7, 9, 11, 13, 15, 17, 19, 21]
\end{verbatim}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \(\left(\frac{1}{n}\right)_{n=1}^\infty\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Como reales}
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=} \FloatTok{1} \OperatorTok{/}\NormalTok{ n}
\FunctionTok{print}\NormalTok{([}\FunctionTok{x}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{])}
\CommentTok{\# Como racionales}
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=} \FloatTok{1}\OperatorTok{//}\NormalTok{n}
\FunctionTok{print}\NormalTok{([}\FunctionTok{x}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1.0, 0.5, 0.3333333333333333, 0.25, 0.2, 0.16666666666666666, 0.14285714285714285, 0.125, 0.1111111111111111, 0.1]
\end{verbatim}

\begin{verbatim}
Rational{Int64}[1//1, 1//2, 1//3, 1//4, 1//5, 1//6, 1//7, 1//8, 1//9, 1//10]
\end{verbatim}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \(\left((-1)^n\right)_{n=1}^\infty\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=}\NormalTok{ (}\OperatorTok{{-}}\FloatTok{1}\NormalTok{)}\OperatorTok{\^{}}\NormalTok{n}
\FunctionTok{print}\NormalTok{([}\FunctionTok{x}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[-1, 1, -1, 1, -1, 1, -1, 1, -1, 1]
\end{verbatim}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  \(\left(\left(1+\frac{1}{n}\right)^n\right)_{n=1}^\infty\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=}\NormalTok{ (}\FloatTok{1} \OperatorTok{+} \FloatTok{1} \OperatorTok{/}\NormalTok{ n)}\OperatorTok{\^{}}\NormalTok{n}
\FunctionTok{print}\NormalTok{([}\FunctionTok{x}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[2.0, 2.25, 2.3703703703703702, 2.44140625, 2.4883199999999994, 2.5216263717421135, 2.546499697040712, 2.565784513950348, 2.581174791713198, 2.5937424601000023]
\end{verbatim}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  \(x_1=1\) y \(x_{n+1}=\sqrt{1+x_n}\) \(\forall n\in\mathbb{N}\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=}\NormalTok{ n }\OperatorTok{==} \FloatTok{1}\NormalTok{ ? }\FloatTok{1} \OperatorTok{:} \FunctionTok{sqrt}\NormalTok{(}\FloatTok{1}\FunctionTok{+x}\NormalTok{(n}\OperatorTok{{-}}\FloatTok{1}\NormalTok{))}
\FunctionTok{print}\NormalTok{([}\FunctionTok{x}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Real[1, 1.4142135623730951, 1.5537739740300374, 1.5980531824786175, 1.6118477541252516, 1.616121206508117, 1.6174427985273905, 1.617851290609675, 1.6179775309347393, 1.6180165422314876]
\end{verbatim}

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-limite-grafica-sucesiones}{}}%
\begin{exercise}[]\label{exr-limite-grafica-sucesiones}

Dibujar en una gráfica los 50 primeros términos de las siguientes
sucesiones y deducir si son convergentes o no. En el caso de que sean
convergentes, dar un valor aproximado de su límite.

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Definir una función para el término general y aplicar la función a los
naturales de 1 a 50 usando compresiones de arrays como en el ejercicio
anterior. Después usar la función
\href{https://docs.juliaplots.org/latest/api/\#Plots.scatter-Tuple}{\texttt{scatter}}
del paquete \texttt{Plots} para dibujar el array de términos.

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  \(\left(\frac{n}{4n+2}\right)_{n=1}^\infty\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=}\NormalTok{ n }\OperatorTok{/}\NormalTok{ (}\FloatTok{4}\NormalTok{n }\OperatorTok{+} \FloatTok{2}\NormalTok{)}
\FunctionTok{scatter}\NormalTok{([}\FunctionTok{x}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{50}\NormalTok{], legend}\OperatorTok{=}\ConstantTok{false}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./sucesiones_files/figure-pdf/cell-8-output-1.pdf}

}

\end{figure}

La sucesión converge al número \(0.25\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \(\left(\frac{2^n}{n^2}\right)_{n=1}^\infty\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=} \FloatTok{2}\OperatorTok{\^{}}\NormalTok{n }\OperatorTok{/}\NormalTok{ (}\FloatTok{4}\NormalTok{n }\OperatorTok{+} \FloatTok{2}\NormalTok{)}
\FunctionTok{scatter}\NormalTok{([}\FunctionTok{x}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{50}\NormalTok{], legend}\OperatorTok{=}\ConstantTok{false}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./sucesiones_files/figure-pdf/cell-9-output-1.pdf}

}

\end{figure}

La sucesión diverge.

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \(\left(\frac{(-1)^n}{n}\right)_{n=1}^\infty\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=}\NormalTok{ (}\OperatorTok{{-}}\FloatTok{1}\NormalTok{)}\OperatorTok{\^{}}\NormalTok{n }\OperatorTok{/}\NormalTok{ n}
\FunctionTok{scatter}\NormalTok{([}\FunctionTok{x}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{50}\NormalTok{], legend}\OperatorTok{=}\ConstantTok{false}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./sucesiones_files/figure-pdf/cell-10-output-1.pdf}

}

\end{figure}

La sucesión converge al \(0\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  \(\left(\left(1+\frac{1}{n}\right)^n\right)_{n=1}^\infty\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=}\NormalTok{ (}\FloatTok{1} \OperatorTok{+} \FloatTok{1} \OperatorTok{/}\NormalTok{ n)}\OperatorTok{\^{}}\NormalTok{n}
\FunctionTok{scatter}\NormalTok{([}\FunctionTok{x}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{50}\NormalTok{], legend}\OperatorTok{=}\ConstantTok{false}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./sucesiones_files/figure-pdf/cell-11-output-1.pdf}

}

\end{figure}

La sucesión converge aproximadamente a \(2.7\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  \(x_1 = 0.5\) y \(x_{n+1}=\frac{3}{2+x_n}\) \(\forall n\in\mathbb{N}\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=}\NormalTok{  n }\OperatorTok{==} \FloatTok{1}\NormalTok{ ? }\FloatTok{0.5} \OperatorTok{:} \FloatTok{3}\OperatorTok{/}\NormalTok{(}\FloatTok{2}\FunctionTok{+x}\NormalTok{(n}\OperatorTok{{-}}\FloatTok{1}\NormalTok{))}
\FunctionTok{scatter}\NormalTok{([}\FunctionTok{x}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{50}\NormalTok{], legend}\OperatorTok{=}\ConstantTok{false}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./sucesiones_files/figure-pdf/cell-12-output-1.pdf}

}

\end{figure}

La sucesión converge aproximadamente a \(1\).

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-limite-sucesiones}{}}%
\begin{exercise}[]\label{exr-limite-sucesiones}

Calcular el límite, si existe, de las siguiente sucesiones.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  \(\left(\frac{1}{n}\right)_{n=1}^\infty\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Definir una función para el término general usar la función
\href{https://docs.juliahub.com/SymPy/KzewI/1.0.31/Tutorial/calculus/\#Limits-1}{\texttt{limit}}
del paquete \texttt{SymPy} para calcular el límite de la sucesión.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{SymPy}
\PreprocessorTok{@syms}\NormalTok{ n}\OperatorTok{::}\DataTypeTok{(integer}\NormalTok{, positive)  }\CommentTok{\# Declaración de la variable simbólica n.}
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=} \FloatTok{1}\OperatorTok{/}\NormalTok{n}
\FunctionTok{limit}\NormalTok{(}\FunctionTok{x}\NormalTok{(n), n}\OperatorTok{=\textgreater{}}\NormalTok{oo)}
\end{Highlighting}
\end{Shaded}

$0$

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \(\left((-1)^n\right)_{n=1}^\infty\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\PreprocessorTok{@syms}\NormalTok{ n}\OperatorTok{::}\DataTypeTok{(integer}\NormalTok{, positive)}
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=}\NormalTok{ (}\OperatorTok{{-}}\FloatTok{1}\NormalTok{)}\OperatorTok{\^{}}\NormalTok{n}
\FunctionTok{limit}\NormalTok{(}\FunctionTok{x}\NormalTok{(n), n}\OperatorTok{=\textgreater{}}\NormalTok{oo)}
\end{Highlighting}
\end{Shaded}

$\text{NaN}$

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \(\left(\left(1+\frac{1}{n}\right)^n\right)_{n=1}^\infty\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\PreprocessorTok{@syms}\NormalTok{ n}\OperatorTok{::}\DataTypeTok{(integer}\NormalTok{, positive)}
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=}\NormalTok{ (}\FloatTok{1} \OperatorTok{+} \FloatTok{1} \OperatorTok{/}\NormalTok{ n)}\OperatorTok{\^{}}\NormalTok{n}
\FunctionTok{limit}\NormalTok{(}\FunctionTok{x}\NormalTok{(n), n}\OperatorTok{=\textgreater{}}\NormalTok{oo)}
\end{Highlighting}
\end{Shaded}

$e$

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-calculo-pi}{}}%
\begin{exercise}[]\label{exr-calculo-pi}

En el siglo III A.C
\href{https://es.wikipedia.org/wiki/Arqu\%C3\%ADmedes}{Arquímedes} usó
el
\href{https://es.wikipedia.org/wiki/M\%C3\%A9todo_por_agotamiento}{método
por agotamiento} para calcular el área encerrada por una circunferencia
(y de paso el valor de \(\pi\)). La idea consiste en inscribir la
circunferencia en polígonos regulares con un número de lados cada vez
mayor.

\begin{figure}

{\centering \includegraphics{./img/sucesiones/poligonos-circunferencia.png}

}

\caption{Aproximación del área de una circunferencia mediante polígonos
regulares}

\end{figure}

El área de estos polígonos puede calcularse fácilmente descomponiendo
los polígonos regulares en triángulos como en el siguiente ejemplo.

\begin{figure}

{\centering 

\input{././img/sucesiones/area-poligono-regular-inscrito.tex}

}

\caption{Descomposición de un hexágono en triángulos}

\end{figure}

En el caso de los polígonos inscritos dentro de la circunferencia, como
dos de los lados siempre coinciden con el radio de la circunferencia
\(r\), el área del polígono de \(n\) lados puede calcularse con la
fórmula

\[
a_n = \frac{1}{2}nr^2\operatorname{sen}\left(\frac{360}{n}\right)
\]

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Calcular el área de los polígonos de \(10^i\) lados, para
  \(i=1,\ldots, 6\) tomando \(r=1\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{a}\NormalTok{(n) }\OperatorTok{=} \FunctionTok{n*sind}\NormalTok{(}\FloatTok{360}\OperatorTok{/}\NormalTok{n)}\OperatorTok{/}\FloatTok{2}
\FunctionTok{print}\NormalTok{([}\FunctionTok{a}\NormalTok{(}\FloatTok{10}\OperatorTok{\^{}}\NormalTok{i) for i }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{6}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[2.938926261462366, 3.1395259764656687, 3.1415719827794755, 3.141592446881286, 3.141592651522708, 3.1415926535691225]
\end{verbatim}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Dibujar con los primeros 50 términos de la sucesión de las areas de
  los polígonos tomando \(r=1\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{a}\NormalTok{(n) }\OperatorTok{=} \FunctionTok{n*sind}\NormalTok{(}\FloatTok{360}\OperatorTok{/}\NormalTok{n)}\OperatorTok{/}\FloatTok{2}
\FunctionTok{scatter}\NormalTok{([}\FunctionTok{a}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{50}\NormalTok{], legend}\OperatorTok{=}\ConstantTok{false}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./sucesiones_files/figure-pdf/cell-17-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Calcular el límite de la sucesión de las areas de los polígonos
  tomando \(r=1\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{SymPy}
\PreprocessorTok{@syms}\NormalTok{ n}\OperatorTok{::}\DataTypeTok{(integer}\NormalTok{, positive)}
\FunctionTok{a}\NormalTok{(n) }\OperatorTok{=} \FunctionTok{n*sin}\NormalTok{(}\FloatTok{2}\NormalTok{pi}\OperatorTok{/}\NormalTok{n)}\OperatorTok{/}\FloatTok{2}
\FunctionTok{limit}\NormalTok{(}\FunctionTok{a}\NormalTok{(n), n}\OperatorTok{=\textgreater{}}\NormalTok{oo)}
\end{Highlighting}
\end{Shaded}

$3.14159265358979$

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Usando el resultado anterior, calcular el area del círculo de radio
  \(r\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{SymPy}
\PreprocessorTok{@syms}\NormalTok{ n}\OperatorTok{::}\DataTypeTok{(integer}\NormalTok{, positive), r}
\FunctionTok{a}\NormalTok{(n) }\OperatorTok{=}\NormalTok{ n}\OperatorTok{*}\NormalTok{r}\OperatorTok{\^{}}\FloatTok{2}\FunctionTok{*sin}\NormalTok{(}\FloatTok{2}\NormalTok{pi}\OperatorTok{/}\NormalTok{n)}\OperatorTok{/}\FloatTok{2}
\FunctionTok{limit}\NormalTok{(}\FunctionTok{a}\NormalTok{(n), n}\OperatorTok{=\textgreater{}}\NormalTok{oo)}
\end{Highlighting}
\end{Shaded}

$3.14159265358979 r^{2}$

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-subsucesiones}{}}%
\begin{exercise}[]\label{exr-subsucesiones}

Dada la sucesión \(x_1=1\) y \(x_{n+1}=1+\frac{1}{n}\)
\(\forall n\in\mathbb{N}\), se pide:

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Dibujar la gráfica de los 10 primeros términos de la sucesión. ¿Es una
  sucesión monótona?
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=}\NormalTok{  n }\OperatorTok{==} \FloatTok{1}\NormalTok{ ? }\FloatTok{1} \OperatorTok{:} \FloatTok{1} \OperatorTok{+} \FloatTok{1} \OperatorTok{/} \FunctionTok{x}\NormalTok{(n}\OperatorTok{{-}}\FloatTok{1}\NormalTok{)}
\FunctionTok{scatter}\NormalTok{([}\FunctionTok{x}\NormalTok{(n) for n }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{], legend}\OperatorTok{=}\ConstantTok{false}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./sucesiones_files/figure-pdf/cell-20-output-1.pdf}

}

\end{figure}

La sucesión no es monótona.

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Dibujar la gráfica de los 5 primeros términos de las subsucesiones con
  los términos pares e impares. ¿Son monótonas?
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}\NormalTok{, }\BuiltInTok{LaTeXStrings}
\FunctionTok{x}\NormalTok{(n) }\OperatorTok{=}\NormalTok{  n }\OperatorTok{==} \FloatTok{1}\NormalTok{ ? }\FloatTok{1} \OperatorTok{:} \FloatTok{1} \OperatorTok{+} \FloatTok{1} \OperatorTok{/} \FunctionTok{x}\NormalTok{(n}\OperatorTok{{-}}\FloatTok{1}\NormalTok{)}
\NormalTok{n1 }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{2}\OperatorTok{:}\FloatTok{10}
\NormalTok{n2 }\OperatorTok{=} \FloatTok{2}\OperatorTok{:}\FloatTok{2}\OperatorTok{:}\FloatTok{10}
\FunctionTok{scatter}\NormalTok{(n1, }\FunctionTok{x}\NormalTok{.(n1), label}\OperatorTok{=}\NormalTok{L}\StringTok{"}\SpecialCharTok{$}\NormalTok{x\_}\StringTok{\{2n{-}1\}}\SpecialCharTok{$}\StringTok{")}
\NormalTok{scatter}\StringTok{!(n2, x.(n2), label=L"}\OperatorTok{$}\NormalTok{x\_\{}\FloatTok{2}\NormalTok{n\}}\OperatorTok{$}\StringTok{")}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./sucesiones_files/figure-pdf/cell-21-output-1.pdf}

}

\end{figure}

La sucesión de los términos impares es creciente y la de los pares es
decreciente.

\end{tcolorbox}

\end{exercise}

\hypertarget{ejercicios-propuestos}{%
\section{Ejercicios propuestos}\label{ejercicios-propuestos}}

\leavevmode\vadjust pre{\hypertarget{exr-sucesiones-propuesto-1}{}}%
\begin{exercise}[]\label{exr-sucesiones-propuesto-1}

Calcular el décimo término de la sucesión
\(\left(\frac{3n^2+n}{6n^2-1}\right)_{n=1}^\infty\).

\vspace{18pt}*Hint: *

Introducir hasta 5 decimales

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-sucesiones-propuesto-2}{}}%
\begin{exercise}[]\label{exr-sucesiones-propuesto-2}

Calcular los 10 primeros términos de la sucesión
\(\left(\frac{3n^2+n}{6n^2-1}\right)_{n=1}^\infty\) y averiguar hacia
dónde converge.

${\quad\Box}$ No converge

${\quad\Box}$ 0.5

${\quad\Box}$ 1

${\quad\Box}$ 1.5

${\quad\Box}$ 0

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-sucesiones-propuesto-3}{}}%
\begin{exercise}[]\label{exr-sucesiones-propuesto-3}

¿Cuál de las siguientes gráficas corresponde a la sucesión \(x_1=3\) y
\(x_{n+1}=\sqrt{2x_n}\) \(\forall n\in\mathbb{N}\).

insert image here

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-sucesiones-propuesto-4}{}}%
\begin{exercise}[]\label{exr-sucesiones-propuesto-4}

A la vista de la gráfica de los 20 primeros términos de la sucesión
\(\left(\frac{2^n}{n!}\right)_{n=1}^\infty\), ¿crees que la sucesión
converge?

${\quad\Box}$ Si

${\quad\Box}$ No

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-sucesiones-propuesto-5}{}}%
\begin{exercise}[]\label{exr-sucesiones-propuesto-5}

A la vista de la gráfica de los 10 primeros términos de la sucesión
\(\left(\frac{n^n}{n!}\right)_{n=1}^\infty\), ¿crees que la sucesión
converge?

${\quad\Box}$ Si

${\quad\Box}$ No

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-sucesiones-propuesto-6}{}}%
\begin{exercise}[]\label{exr-sucesiones-propuesto-6}

A la vista de la gráfica de los 20 primeros términos de la sucesión dada
por \(x_1=1\) y \(x_{n+1}=\sqrt{x_n+2}\) \(\forall n\in \mathbb{N}\),
¿crees que la sucesión converge?

${\quad\Box}$ Si

${\quad\Box}$ No

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-sucesiones-propuesto-7}{}}%
\begin{exercise}[]\label{exr-sucesiones-propuesto-7}

¿Cuál es el límite de la sucesión
\(\left(\left(1+\frac{2}{n}\right)^n\right)_{n=1}^\infty\)

\vspace{18pt}*Hint: *

Introducir hasta 5 decimales

\end{exercise}

\bookmarksetup{startatroot}

\hypertarget{funciones-elementales}{%
\chapter{Funciones elementales}\label{funciones-elementales}}

\hypertarget{ejercicios-resueltos-1}{%
\section{Ejercicios Resueltos}\label{ejercicios-resueltos-1}}

Para la realización de esta práctica se requieren los siguientes
paquetes:

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots  }\CommentTok{\# Para el dibujo de gráficas.}
\CommentTok{\#plotlyjs()  \# Para obtener gráficos interactivos.}
\ImportTok{using} \BuiltInTok{SymPy }\CommentTok{\# Para el cálculo simbólico.}
\ImportTok{using} \BuiltInTok{MTH229 }\CommentTok{\# Para restringir la gráfica de una función a su dominio.}
\ImportTok{using} \BuiltInTok{LaTeXStrings  }\CommentTok{\# Para usar código LaTeX en los gráficos.}
\end{Highlighting}
\end{Shaded}

\leavevmode\vadjust pre{\hypertarget{exr-grafica-funcion-tabla}{}}%
\begin{exercise}[]\label{exr-grafica-funcion-tabla}

La siguiente tabla contiene el número de bacterias en un cultivo cada
hora que pasa.

\begin{longtable}[]{@{}cc@{}}
\toprule()
Horas & Bacterias \\
\midrule()
\endhead
0 & 1 \\
1 & 2 \\
2 & 4 \\
3 & 8 \\
4 & 16 \\
5 & 32 \\
6 & 64 \\
7 & 128 \\
\bottomrule()
\end{longtable}

Dibujar una gráfica con la evolución del la población de bacterias.

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Definir los valores de las horas en un vector \texttt{x} y el número de
bacterias en otro \texttt{y} y luego utilizar la función
\href{https://aprendeconalf.es/manual-julia/graficos.html\#a\%C3\%B1adir-puntos-a-una-gr\%C3\%A1fica}{\texttt{scatter(x,y)}}
del paquete \texttt{Plots} para dibujar una gráfica de puntos.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\NormalTok{horas }\OperatorTok{=} \FloatTok{0}\OperatorTok{:}\FloatTok{7}
\NormalTok{bacterias }\OperatorTok{=}\NormalTok{ [}\FloatTok{1}\NormalTok{, }\FloatTok{2}\NormalTok{, }\FloatTok{4}\NormalTok{, }\FloatTok{8}\NormalTok{, }\FloatTok{16}\NormalTok{, }\FloatTok{32}\NormalTok{, }\FloatTok{64}\NormalTok{, }\FloatTok{128}\NormalTok{]}
\FunctionTok{scatter}\NormalTok{(horas, bacterias, xlab}\OperatorTok{=}\StringTok{"Horas"}\NormalTok{, ylab}\OperatorTok{=}\StringTok{"Bacterias"}\NormalTok{, title}\OperatorTok{=}\StringTok{"Evolución de la población de bacterias"}\NormalTok{, legend}\OperatorTok{=}\ConstantTok{false}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-3-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

¿Los pares dados en la tabla forman una función?

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Si, porque para cada hora hay a lo sumo un número de bacterias con el
que se relaciona.

\end{tcolorbox}

¿Qué fórmula crees que explica la evolución del número de bacterias en
función de las horas que pasan? Dibuja en la gráfica anterior la función
con esa fórmula.

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Para añadir una nueva gráfica a una anterior se añade un signo de
exclamación \texttt{!} a la función de graficación. Para una gráfica de
líneas, utilizar la función
\href{https://aprendeconalf.es/manual-julia/graficos.html\#gr\%C3\%A1fica-de-una-funci\%C3\%B3n-de-una-variable}{\texttt{plot!}}
del paquete \texttt{Plots}, pasándole el nombre de la función si se ha
definido previamente o la
\href{https://aprendeconalf.es/manual-julia/funciones.html\#funciones-an\%C3\%B3nimas}{definición
anónima de la función}

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{plot!}\NormalTok{(x }\OperatorTok{{-}\textgreater{}} \FloatTok{2}\OperatorTok{\^{}}\NormalTok{x)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-4-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-resolucion-grafica-ecuacion}{}}%
\begin{exercise}[]\label{exr-resolucion-grafica-ecuacion}

En el lanzamiento vertical de un objeto, la posición que ocupa el objeto
en cada instante \(t\), viene dado por la función

\[
y(t) =  y_0+v_0t+\frac{1}{2}gt^2
\]

donde \(y_0\) es la altura inicial del objeto, \(v_0\) la velocidad
inicial con que se lanza, y \(g\) es la aceleración de la gravedad. Una
pelota se lanza verticalmente desde la ventada de un edificio a 5 m de
altura, con una velocidad inicial de \(10\) m/s. Dibujar la gráfica de
la posición de la pelota en función del tiempo, tomando una aceleración
de la gravedad \(g=-9.8\) m/s².

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Declarar \(t\) como una variable simbólica usando el paquete
\href{https://docs.juliahub.com/SymPy/KzewI/1.0.29/introduction/\#Symbols-1}{\texttt{SymPy}},
definir después las constantes \(y_0\), \(v_0\) y \(g\), y luego definir
la función \(y(t)\) mediante la fórmula dada.

Para dibujar la gráfica de la función, usar la función \texttt{plot}
pasándole el nombre de la función. Como no tienen sentido los instantes
negativos, ni las posiciones negativas, restringir la ventana de
graficación a valores de \(t\) y de \(y\) positivos usando los
parámetros
\href{https://aprendeconalf.es/manual-julia/graficos.html\#ventana-de-graficaci\%C3\%B3n}{\texttt{xlim}}
e
\href{https://aprendeconalf.es/manual-julia/graficos.html\#ventana-de-graficaci\%C3\%B3n}{\texttt{ylim}}.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}\NormalTok{, }\BuiltInTok{SymPy}
\PreprocessorTok{@vars}\NormalTok{ t  }\CommentTok{\#Declaramos t como una variable simbólica}
\NormalTok{y₀ }\OperatorTok{=} \FloatTok{5}
\NormalTok{v₀ }\OperatorTok{=} \FloatTok{10}
\KeywordTok{const}\NormalTok{ gravedad }\OperatorTok{=} \OperatorTok{{-}}\FloatTok{9.8}  \CommentTok{\#Declaramos la gravedad como una constante}
\FunctionTok{y0}\NormalTok{(t) }\OperatorTok{=}\NormalTok{ y₀}\OperatorTok{+}\NormalTok{v₀}\OperatorTok{*}\NormalTok{t}\OperatorTok{+} \FloatTok{1}\OperatorTok{/}\FloatTok{2}\OperatorTok{*}\NormalTok{gravedad}\OperatorTok{*}\NormalTok{t}\OperatorTok{\^{}}\FloatTok{2}
\FunctionTok{plot}\NormalTok{(y0, xlims}\OperatorTok{=}\NormalTok{(}\FloatTok{0}\NormalTok{,}\FloatTok{3}\NormalTok{), ylims}\OperatorTok{=}\NormalTok{(}\FloatTok{0}\NormalTok{,}\FloatTok{15}\NormalTok{), label}\OperatorTok{=}\StringTok{"Pelota"}\NormalTok{, xlab}\OperatorTok{=}\StringTok{"Tiempo (s)"}\NormalTok{, ylab}\OperatorTok{=}\StringTok{"Altura (m)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-5-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

Al mismo tiempo que se lanza la pelota, un ascensor exterior baja por la
fachada del mismo edificio desde una altura de \(8\) m con una velocidad
constante de \(5\) m/s. Dibujar la gráfica de la posición del ascensor
junto a la gráfica de la pelota.

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

La función que define la posición del ascensor que baja desde una altura
\(y_1\) con una velocidad constante \(v_1\) en cada instante \(t\) es
\(y(t) = y_1-v_1t\).

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{y₁ }\OperatorTok{=} \FloatTok{8}
\NormalTok{v₁ }\OperatorTok{=} \FloatTok{2}
\FunctionTok{y1}\NormalTok{(t) }\OperatorTok{=}\NormalTok{ y₁}\OperatorTok{{-}}\NormalTok{v₁}\OperatorTok{*}\NormalTok{t}
\FunctionTok{plot!}\NormalTok{(y1, label}\OperatorTok{=}\StringTok{"Ascensor"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-6-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

¿En qué instantes el ascensor estará a la misma altura de la pelota?
Dibujar los puntos correspondientes a esos instantes en la gráfica
anterior.

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sol }\OperatorTok{=} \FunctionTok{solve}\NormalTok{(}\FunctionTok{y0}\NormalTok{(t)}\FunctionTok{{-}y1}\NormalTok{(t))}
\FunctionTok{print}\NormalTok{(}\StringTok{"Instantes: "}\NormalTok{, sol)}
\FunctionTok{scatter!}\NormalTok{(sol, }\FunctionTok{y1}\NormalTok{.(sol), label}\OperatorTok{=}\StringTok{"Intersección"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Instantes: Sym[0.282613815574341, 2.16636577626239]
\end{verbatim}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-7-output-2.pdf}

}

\end{figure}

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-grafica-funcion-polinomica}{}}%
\begin{exercise}[]\label{exr-grafica-funcion-polinomica}

El volumen de un globo esférico depende del radio según la función
\(v(r)= \frac{4}{3}\pi r^3\). Calcular la función que expresa el radio
en función del volumen y dibujar su gráfica.

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Declarar las variables simbólicas \texttt{r} y \texttt{v} usando el
paquete \texttt{SymPy} y definir la función \texttt{vol(r)} que expresa
el volumen del globo en función del radio.

Después utilizar la función
\href{https://docs.juliahub.com/SymPy/KzewI/1.0.29/introduction/\#The-solve-function-1}{\texttt{solve}}
del paquete \texttt{SymPy} para despejar \texttt{r} de la ecuación
\texttt{v-vol(r)=0}.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}\NormalTok{, }\BuiltInTok{SymPy}
\PreprocessorTok{@vars}\NormalTok{ r v}
\FunctionTok{vol}\NormalTok{(r) }\OperatorTok{=} \FloatTok{4}\OperatorTok{/}\FloatTok{3}\OperatorTok{*}\ConstantTok{pi}\OperatorTok{*}\NormalTok{r}\OperatorTok{\^{}}\FloatTok{3}
\NormalTok{rad }\OperatorTok{=} \FunctionTok{solve}\NormalTok{(}\FunctionTok{v{-}vol}\NormalTok{(r),r)[}\FloatTok{1}\NormalTok{]}
\FunctionTok{plot}\NormalTok{(rad, xlab}\OperatorTok{=}\StringTok{"Volumen (m³)"}\NormalTok{, ylab}\OperatorTok{=}\StringTok{"Radio (m)"}\NormalTok{, legend}\OperatorTok{=}\ConstantTok{false}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-8-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

Si empezamos a introducir helio en el globo de manera que su volumen a
los \(t\) minutos viene dado por la función \(v(t)=t^2+2t\), dibujar la
gráfica de la función que da el radio en cada instante.

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Declarar las variables simbólicas \texttt{t} usando el paquete
\texttt{SymPy} y definir la función \texttt{vol(t)} que expresa el
volumen del globo en función del tiempo.

Después utilizar a el operador de composición \(\circ\) para componer la
función del volumen con la función del radio.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\PreprocessorTok{@vars}\NormalTok{ t}
\FunctionTok{vol}\NormalTok{(t)}\OperatorTok{=}\NormalTok{t}\OperatorTok{\^{}}\FloatTok{2}\OperatorTok{+}\FloatTok{2}\NormalTok{t}
\FunctionTok{plot}\NormalTok{(rad}\OperatorTok{∘}\NormalTok{vol, xlim}\OperatorTok{=}\NormalTok{(}\FloatTok{0}\NormalTok{,}\FloatTok{10}\NormalTok{), xlab}\OperatorTok{=}\StringTok{"Tiempo (min)"}\NormalTok{, ylab}\OperatorTok{=}\StringTok{"Radio (m)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-9-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

Si el globo explota cuando el radio alcanza los 3 m, ¿cuándo explotará
el globo?

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sol }\OperatorTok{=} \FunctionTok{solve}\NormalTok{((rad}\OperatorTok{∘}\NormalTok{vol)(t)}\OperatorTok{{-}}\FloatTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

$\left[ \begin{array}{r}-11.6816354332674\\9.68163543326738\end{array} \right]$

El globo explotará a los 9.68163543326738 minutos.

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-grafica-funcion-polinomica}{}}%
\begin{exercise}[]\label{exr-grafica-funcion-polinomica}

Dibujar la gráfica de la función

\[
f(x) = 2x^3-3x^2-12x+4
\]

en el intervalo \([-3,4]\) y determinar, observando la gráfica, lo
siguiente:

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Definir la función y usar la función
\href{https://docs.juliaplots.org/latest/tutorial/\#Basic-Plotting:-Line-Plots}{\texttt{plot}}
del paquete \texttt{Plots}.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}\NormalTok{, }\BuiltInTok{LaTeXStrings}
\FunctionTok{f}\NormalTok{(x) }\OperatorTok{=} \FloatTok{2}\NormalTok{x}\OperatorTok{\^{}}\FloatTok{3}\OperatorTok{{-}}\FloatTok{3}\NormalTok{x}\OperatorTok{\^{}}\FloatTok{2}\OperatorTok{{-}}\FloatTok{12}\NormalTok{x}\OperatorTok{+}\FloatTok{4}
\FunctionTok{plot}\NormalTok{(f, }\OperatorTok{{-}}\FloatTok{3}\NormalTok{, }\FloatTok{4}\NormalTok{, label}\OperatorTok{=}\NormalTok{L}\StringTok{"}\SpecialCharTok{$}\NormalTok{f}\StringTok{(x) = 2x\^{}3{-}3x\^{}2{-}12x+4}\SpecialCharTok{$}\StringTok{")}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-12-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Dominio
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\(Dom(f)=\mathbb{R}\)

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Imagen
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\(Im(f)=\mathbb{R}\)

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Raíces
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{SymPy}
\PreprocessorTok{@syms}\NormalTok{ x}
\FunctionTok{f}\NormalTok{(x) }\OperatorTok{=} \FloatTok{2}\NormalTok{x}\OperatorTok{\^{}}\FloatTok{3}\OperatorTok{{-}}\FloatTok{3}\NormalTok{x}\OperatorTok{\^{}}\FloatTok{2}\OperatorTok{{-}}\FloatTok{12}\NormalTok{x}\OperatorTok{+}\FloatTok{4}
\NormalTok{raices }\OperatorTok{=} \FunctionTok{solve}\NormalTok{(}\FunctionTok{f}\NormalTok{(x))  }\CommentTok{\# Solución exacta}
\FunctionTok{print}\NormalTok{(raices)}
\FunctionTok{N}\NormalTok{(raices)  }\CommentTok{\# Solución aproximada con decimales}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Sym[-2, 7/4 - sqrt(33)/4, sqrt(33)/4 + 7/4]
\end{verbatim}

\begin{verbatim}
3-element Vector{Real}:
 -2
  0.313859338365492835037347132945267670444933885504301908075030632358524819635648
  3.186140661634507164962652867054732329555066114495698091924969367641475180364343
\end{verbatim}

Hay tres raíces en \(x=-2\), \(x=0.31\) y \(x=3.19\) aproximadamente.

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Signo
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Intervalos con \(f(x)\) negativa: \((-\infty, -2)\cup (0.31,3.19)\).\\
Intervalos con \(f(x)\) positiva: \((-2,0.31)\cup (3.19,\infty)\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Crecimiento
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Intervalos con \(f(x)\) creciente: \((-\infty, -1)\cup (2,\infty)\).\\
Intervalos con \(f(x)\) decreciente: \((-1,2)\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Extremos
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Máximo relativo en \(x=-1\) y el valor máximo es \(f(-1)=11\).\\
Mínimo relativo en \(x=2\) y el valor del mínimo es \(f(2)=-16\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Concavidad
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Intervalos de concavidad hacia arriba: \((0.5,\infty)\).\\
Intervalos de concavidad hacia abajo: \((-\infty, 0.5)\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Puntos de inflexión
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Punto de inflexión en \(x=0.5\).

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-grafica-funcion-racional}{}}%
\begin{exercise}[]\label{exr-grafica-funcion-racional}

Dibujar la gráfica de la función

\[
g(t) = \frac{t^4+19t^2-5}{t^4+9t^2-10}
\]

en el intervalo \([-8,8]\) y determinar, observando la gráfica, lo
siguiente:

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Usar la función \texttt{plot} como en el ejercicio anterior con el
parámetro \texttt{aspect\_ratio=1.0} para que los ejes tengan la misma
escala.

Para respetar las discontinuidades autilizar la función
\texttt{rangeclamp()} del paquete \texttt{MTH229}.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{g}\NormalTok{(t) }\OperatorTok{=}\NormalTok{ (t}\OperatorTok{\^{}}\FloatTok{4}\OperatorTok{+}\FloatTok{19}\NormalTok{t}\OperatorTok{\^{}}\FloatTok{2}\OperatorTok{{-}}\FloatTok{5}\NormalTok{) }\OperatorTok{/}\NormalTok{ (t}\OperatorTok{\^{}}\FloatTok{4}\OperatorTok{+}\FloatTok{9}\NormalTok{t}\OperatorTok{\^{}}\FloatTok{2}\OperatorTok{{-}}\FloatTok{10}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{rangeclamp}\NormalTok{(g), }\OperatorTok{{-}}\FloatTok{8}\NormalTok{, }\FloatTok{8}\NormalTok{, aspect\_ratio}\OperatorTok{=}\FloatTok{1.0}\NormalTok{, ylims}\OperatorTok{=}\NormalTok{(}\OperatorTok{{-}}\FloatTok{5}\NormalTok{,}\FloatTok{5}\NormalTok{) , xticks }\OperatorTok{=}\FunctionTok{Vector}\NormalTok{(}\OperatorTok{{-}}\FloatTok{10}\OperatorTok{:}\FloatTok{10}\NormalTok{), yticks }\OperatorTok{=} \FunctionTok{Vector}\NormalTok{(}\OperatorTok{{-}}\FloatTok{5}\OperatorTok{:}\FloatTok{5}\NormalTok{), label}\OperatorTok{=}\NormalTok{L}\StringTok{"}\SpecialCharTok{$}\NormalTok{g}\StringTok{(t) = }\SpecialCharTok{\textbackslash{}f}\StringTok{rac\{t\^{}4+19t\^{}2{-}5\}\{t\^{}4+9t\^{}2{-}10\}}\SpecialCharTok{$}\StringTok{")}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-14-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Dominio. ¿Qué pasa si aplicamos la función a algún valor fuera de su
  dominio?
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\(Dom(f)=\mathbb{R}\setminus\{-1,1\}\)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{g}\NormalTok{(}\OperatorTok{{-}}\FloatTok{1}\NormalTok{), }\FunctionTok{g}\NormalTok{(}\FloatTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
(Inf, Inf)
\end{verbatim}

Como se observa, al aplicar la función a \(-1\) y \(1\) se obtiene
\(\infty\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Imagen
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\(Im(f)=\mathbb{R}\setminus (0.5,1]\)

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Asíntotas. Dibujarlas.
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Buscar las asíntotas verticales en los puntos fuera del dominio de la
función.

Para dibujar asíntotas verticales usar la función
\href{https://docs.juliaplots.org/latest/api/\#Plots.vline-Tuple}{\texttt{vline}}
del paquete \texttt{Plots}, y para dibujar las asíntotas horizontales
usar la función
\href{https://docs.juliaplots.org/latest/api/\#Plots.hline-Tuple}{\texttt{hline}}.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{vline!}\NormalTok{([}\OperatorTok{{-}}\FloatTok{1}\NormalTok{,}\FloatTok{1}\NormalTok{], label}\OperatorTok{=}\StringTok{"Asíntotas verticales"}\NormalTok{)}
\FunctionTok{hline!}\NormalTok{([}\FloatTok{1}\NormalTok{], label}\OperatorTok{=}\StringTok{"Asíntotas horizontales"}\NormalTok{, legend}\OperatorTok{=:}\NormalTok{bottomright)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-16-output-1.pdf}

}

\end{figure}

Asíntotas verticales en \(x=-1\) y \(x=1\).\\
Asíntotas horizontales en \(y=1\).\\
No hay asíntotas oblicuas.

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Raíces
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Hay dos raíces en \(x=-0.5\) y \(x=0.5\) aproximadamente.

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Signo
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Intervalos con \(f(x)\) positiva:
\((-\infty,-1)\cup (-0.5,0.5)\cup (1,\infty)\).\\
Intervalos con \(f(x)\) negativa: \((-1,-0.5)\cup (0.5,1)\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Crecimiento
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Intervalos con \(f(x)\) creciente: \((-\infty, -1)\cup (-1,0)\).\\
Intervalos con \(f(x)\) decreciente: \((0,1)\cup (1,\infty)\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Extremos
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Máximo relativo en \(x=0\) y el valor máximo es \(g(0)=0.5\).\\
No hay mínimos relativos.

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Concavidad
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Intervalos de concavidad hacia arriba:
\((-\infty,-1)\cup (1,\infty)\).\\
Intervalos de concavidad hacia abajo: \((-1,1)\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Puntos de inflexión
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

No hay puntos de inflexión.

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-funciones-exponenciales}{}}%
\begin{exercise}[]\label{exr-funciones-exponenciales}

Dibujar la gráficas de las siguientes funciones exponenciales \(2^x\),
\(e^x\), \(0.5^x\), \(0.7^x\) y responder a las siguientes preguntas
comparando las gráficas.

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}\NormalTok{, }\BuiltInTok{LaTeXStrings}
\FunctionTok{plot}\NormalTok{(}\FloatTok{2}\OperatorTok{\^{}}\NormalTok{x, }\OperatorTok{{-}}\FloatTok{2}\NormalTok{, }\FloatTok{2}\NormalTok{, label}\OperatorTok{=}\NormalTok{L}\StringTok{"}\SpecialCharTok{$}\StringTok{2\^{}}\NormalTok{x}\SpecialCharTok{$}\StringTok{")}
\NormalTok{plot}\StringTok{!(exp(x), label=L"}\OperatorTok{$}\NormalTok{e}\OperatorTok{\^{}}\NormalTok{x}\OperatorTok{$}\StringTok{")}
\FunctionTok{plot!}\NormalTok{(}\FloatTok{0.5}\OperatorTok{\^{}}\NormalTok{x, label}\OperatorTok{=}\NormalTok{L}\StringTok{"}\SpecialCharTok{$}\StringTok{2\^{}}\NormalTok{x}\SpecialCharTok{$}\StringTok{")}
\NormalTok{plot}\StringTok{!(0.7\^{}x, label=L"}\OperatorTok{$}\FloatTok{2}\OperatorTok{\^{}}\NormalTok{x}\OperatorTok{$}\StringTok{")}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-17-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  ¿Cuál es el dominio de una función exponencial?
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\(\mathbb{R}\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  ¿Cuál es la imagen de una función exponencial?
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\(\mathbb{R}^+\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  ¿Cómo es el crecimiento de una función exponencial?
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\(a^x\) es creciente si \(a>1\) y decreciente si \(0<a<1\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  ¿Tienen extremos una función exponencial?
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

No

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  ¿Cómo es la curvatura de una función exponencial?
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Es cóncava hacia arriba.

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-funciones-trigonomuxe9tricas}{}}%
\begin{exercise}[]\label{exr-funciones-trigonométricas}

Dibujar la gráficas de las funciones trigonométricas
\(\operatorname{sen}(x)\), \(\operatorname{sen}(x+2)\),
\(\operatorname{sen}(x)+2\), \(\operatorname{sen}(2x)\) y
\(2\operatorname{sen}(x)\), y completar la siguiente tabla estudiando su
periodo y amplitud.

\begin{longtable}[]{@{}lll@{}}
\toprule()
Función & Periodo & Amplitud \\
\midrule()
\endhead
\(\operatorname{sen}(x)\) & & \\
\(\operatorname{sen}(x+2)\) & & \\
\(\operatorname{sen}(x)+2\) & & \\
\(\operatorname{sen}(2x)\) & & \\
\(2\operatorname{sen}(x)\) & & \\
\bottomrule()
\end{longtable}

¿Qué conclusiones sacas?

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

El periodo es el mínimo intervalo en el que la gráfica de la función se
repite, y la amplitud es la mitad de la diferencia entre el máximo y el
mínimo de la función.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}\NormalTok{, }\BuiltInTok{LaTeXStrings}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{sin}\NormalTok{(x), }\OperatorTok{{-}}\FloatTok{2}\OperatorTok{*}\ConstantTok{pi}\NormalTok{, }\FloatTok{2}\OperatorTok{*}\ConstantTok{pi}\NormalTok{, label}\OperatorTok{=}\NormalTok{L}\StringTok{"}\SpecialCharTok{$}\StringTok{\textbackslash{}}\NormalTok{operatorname}\StringTok{\{sen\}(x)}\SpecialCharTok{$}\StringTok{")}
\NormalTok{plot}\StringTok{!(sin(x+2), label=L"}\OperatorTok{$}\FunctionTok{\textbackslash{}operatorname}\DataTypeTok{\{sen\}}\NormalTok{(x}\OperatorTok{+}\FloatTok{2}\NormalTok{)}\OperatorTok{$}\StringTok{")}
\FunctionTok{plot!}\NormalTok{(}\FunctionTok{sin}\NormalTok{(x)}\OperatorTok{+}\FloatTok{2}\NormalTok{, label}\OperatorTok{=}\NormalTok{L}\StringTok{"}\SpecialCharTok{$}\StringTok{\textbackslash{}}\NormalTok{operatorname}\StringTok{\{sen\}(x)+2}\SpecialCharTok{$}\StringTok{")}
\NormalTok{plot}\StringTok{!(sin(2x), label=L"}\OperatorTok{$}\FunctionTok{\textbackslash{}operatorname}\DataTypeTok{\{sen\}}\NormalTok{(}\FloatTok{2}\NormalTok{x)}\OperatorTok{$}\StringTok{")}
\FunctionTok{plot!}\NormalTok{(}\FloatTok{2}\FunctionTok{sin}\NormalTok{(x), label}\OperatorTok{=}\NormalTok{L}\StringTok{"}\SpecialCharTok{$}\StringTok{2\textbackslash{}}\NormalTok{operatorname}\StringTok{\{sen\}(x)}\SpecialCharTok{$}\StringTok{")}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-18-output-1.pdf}

}

\end{figure}

\begin{longtable}[]{@{}lll@{}}
\toprule()
Función & Periodo & Amplitud \\
\midrule()
\endhead
\(\operatorname{sen}(x)\) & \(2\pi\) & 1 \\
\(\operatorname{sen}(x+2)\) & \(2\pi\) & 1 \\
\(\operatorname{sen}(x)+2\) & \(2\pi\) & 1 \\
\(\operatorname{sen}(2x)\) & \(\pi\) & 1 \\
\(2\operatorname{sen}(x)\) & \(2\pi\) & 2 \\
\bottomrule()
\end{longtable}

\end{tcolorbox}

Se observa que al sumar una constante a la función seno o a su
argumento, el periodo y la amplitud no cambian. Sin embargo, si se
multiplica por una constante el seno, cambia la amplitud, y si se
multiplica su argumento, cambia el periodo.

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-funciones-a-trozos}{}}%
\begin{exercise}[]\label{exr-funciones-a-trozos}

Dibujar la gráfica de la función a trozos

\[
h(x)=
\begin{cases}
-2x & \mbox{si } x\leq 0;\\
x^2 & \mbox{si } 0< x \leq 2;\\ 
4 & \mbox{si } 2< x
\end{cases}
\]

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Usar el
\href{https://aprendeconalf.es/manual-julia/estructuras-control.html\#operador-condicional}{operador
condicional} anidado.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{h}\NormalTok{(x) }\OperatorTok{=}\NormalTok{ x}\OperatorTok{\textless{}=}\FloatTok{0}\NormalTok{ ? }\OperatorTok{{-}}\FloatTok{2}\NormalTok{x }\OperatorTok{:}\NormalTok{ x}\OperatorTok{\textless{}=}\FloatTok{2}\NormalTok{ ? x}\OperatorTok{\^{}}\FloatTok{2} \OperatorTok{:} \FloatTok{4}
\FunctionTok{plot}\NormalTok{(h, legend }\OperatorTok{=} \ConstantTok{false}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-19-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-funciones-parametricas}{}}%
\begin{exercise}[]\label{exr-funciones-parametricas}

Una hormiga se mueve sobre el plano real de manera que en cada instante
\(t\) su posición viene dada por las funciones

\[
\begin{cases}
x=\operatorname{sen}(t) \\
y=\operatorname{sen}(2t)
\end{cases}
\]

Dibujar la gráfica de la trayectoria de la hormiga.

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{u1}\NormalTok{(t)}\OperatorTok{=}\FunctionTok{sin}\NormalTok{(t)}
\FunctionTok{v1}\NormalTok{(t)}\OperatorTok{=}\FunctionTok{sin}\NormalTok{(}\FloatTok{2}\NormalTok{t)}
\FunctionTok{plot}\NormalTok{(u1, v1, }\FloatTok{0}\NormalTok{, }\FloatTok{4}\NormalTok{pi, aspect\_ratio}\OperatorTok{=}\FloatTok{1.0}\NormalTok{, legend }\OperatorTok{=} \ConstantTok{false}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./funciones-elementales_files/figure-pdf/cell-20-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

\end{exercise}

\hypertarget{ejercicios-propuestos-1}{%
\section{Ejercicios propuestos}\label{ejercicios-propuestos-1}}

\leavevmode\vadjust pre{\hypertarget{exr-dominio-imagen}{}}%
\begin{exercise}[]\label{exr-dominio-imagen}

¿Cuáles de las siguientes funciones tienen dominio \(\mathbb{R}\) e
imagen \(\mathbb{R}^+\cup\{0\}\)?

${\quad\Box}$ $$|x|$$
${\quad\Box}$ $$\sqrt(x)$$
${\quad\Box}$ $$2^x$$
${\quad\Box}$ $$x^4-2x^3+4x$$
${\quad\Box}$ $$1/x^2$$
(\emph{Select one or more})

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-funciones-logaritmicas}{}}%
\begin{exercise}[]\label{exr-funciones-logaritmicas}

Dibujar las gráficas de las funciones logarítmicas \(\ln(x)\),
\(\log_2(x)\) y \(\log_{0.5}(x)\) y contestar a las siguientes
preguntas.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  ¿Cuál es el dominio de una función logarítmica?
\end{enumerate}

${\quad\Box}$ $$\mathbb{R}^+\cup \{0\}$$
${\quad\Box}$ $$\mathbb{R}$$
${\quad\Box}$ $$\mathbb{R}\setminus\{0\}$$
${\quad\Box}$ $$\mathbb{R}^+$$
${\quad\Box}$ Las otras opciones son falsas.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  ¿Cuál es la imagen de una función logarítmica?
\end{enumerate}

${\quad\Box}$ $$\mathbb{R}\setminus\{0\}$$
${\quad\Box}$ $$\mathbb{R}$$
${\quad\Box}$ Las otras opciones son falsas.

${\quad\Box}$ $$\mathbb{R}^-$$
${\quad\Box}$ $$\mathbb{R}^+$$

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  ¿Cómo es el crecimiento la función logarítmica \(\log_a(x)\)?
\end{enumerate}

${\quad\Box}$ Creciente si $0 < a < 1$

${\quad\Box}$ Creciente si $a<1$

${\quad\Box}$ Decreciente si $0 < a <1$

${\quad\Box}$ Creciente si $a>1$

(\emph{Select one or more})

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  ¿Cómo es la concavidad la función logarítmica \(\log_a(x)\)?
\end{enumerate}

${\quad\Box}$ Cóncava hacia abajo si $a<1$

${\quad\Box}$ Cóncava hacia arriba si $0 < a < 1$

${\quad\Box}$ Cóncava hacia abajo si $0 < a < 1$

${\quad\Box}$ Cóncava hacia arriba si $a>1$

(\emph{Select one or more})

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-funciones-trigonomuxe9tricas}{}}%
\begin{exercise}[]\label{exr-funciones-trigonométricas}

¿Cuál es el periodo y la amplitud de la función \(2\cos(x/2)\)?

${\quad\Box}$ 2π y 1

${\quad\Box}$ π y 2

${\quad\Box}$ 2π y 2

${\quad\Box}$ 4π y 2

${\quad\Box}$ 4π y 1

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-sucesiones-propuesto-3}{}}%
\begin{exercise}[]\label{exr-sucesiones-propuesto-3}

¿Cuál de las gráficas corresponde a la siguiente función paramétrica?

\[
f(t)=
\begin{cases}
\operatorname{sen}(2t)-\cos(t) \\
\operatorname{sen}(t)+\cos(t)
\end{cases}
\]

insert image here

\end{exercise}

\bookmarksetup{startatroot}

\hypertarget{luxedmites-de-funciones-reales}{%
\chapter{Límites de funciones
reales}\label{luxedmites-de-funciones-reales}}

\hypertarget{ejercicios-resueltos-2}{%
\section{Ejercicios Resueltos}\label{ejercicios-resueltos-2}}

Para la realización de esta práctica se requieren los siguientes
paquetes:

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{SymPy  }\CommentTok{\# Para el cálculo simbólico de límites.}
\ImportTok{using} \BuiltInTok{Plots  }\CommentTok{\# Para el dibujo de gráficas.}
\CommentTok{\#plotlyjs() \# Para obtener gráficos interactivos.}
\ImportTok{using} \BuiltInTok{MTH229 }\CommentTok{\# Para restringir la gráfica de una función a su dominio.}
\ImportTok{using} \BuiltInTok{LaTeXStrings  }\CommentTok{\# Para usar código LaTeX en los gráficos.}
\end{Highlighting}
\end{Shaded}

\leavevmode\vadjust pre{\hypertarget{exr-tendencia-1}{}}%
\begin{exercise}[]\label{exr-tendencia-1}

Sea la función \(f(x)=x^2\).

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Estudiar la tendencia de \(f\) cuando \(x\) se aproxima a \(3\) por la
  derecha, evaluando la función en \(x=3+\frac{1}{10i}\) para
  \(i=1,\ldots,10\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Definir la función y aplicar la función a los valores de x indicados
usando
\href{https://aprendeconalf.es/manual-julia/tipos-datos-compuestos.html\#comprensi\%C3\%B3n-de-arrays}{compresiones
de arrays}.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{f}\NormalTok{(x) }\OperatorTok{=}\NormalTok{ x}\OperatorTok{\^{}}\FloatTok{2}
\NormalTok{a }\OperatorTok{=} \FloatTok{3}
\FunctionTok{print}\NormalTok{([}\FunctionTok{f}\NormalTok{(a}\OperatorTok{+}\FloatTok{1}\OperatorTok{/}\FloatTok{10}\NormalTok{i) for i }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[9.610000000000001, 9.302499999999998, 9.20111111111111, 9.150625, 9.1204, 9.100277777777777, 9.085918367346938, 9.075156250000001, 9.06679012345679, 9.060099999999998]
\end{verbatim}

La función tiende a \(9\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Estudiar la tendencia de \(f\) cuando \(x\) se aproxima a \(3\) por la
  izquierda, evaluando la función en \(x=3-\frac{1}{10i}\) para
  \(i=1,\ldots, 10\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{([}\FunctionTok{f}\NormalTok{(a}\OperatorTok{{-}}\FloatTok{1}\OperatorTok{/}\FloatTok{10}\NormalTok{i) for i }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[8.41, 8.7025, 8.801111111111112, 8.850625, 8.8804, 8.900277777777777, 8.914489795918367, 8.925156249999999, 8.933456790123458, 8.940100000000001]
\end{verbatim}

La función también tiende a 9.

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Dibujar la gráfica de los valores de \(f\) evaluados en los apartados
  anteriores diferenciando la tendencia por la izquierda de la tendencia
  por la derecha.
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Definir un vector con los valores de \(x\) y otro con los valores
correspondientes de \(f(x)\) y usar la función
\href{https://docs.juliaplots.org/latest/api/\#Plots.scatter-Tuple}{\texttt{scatter}}
del paquete \texttt{Plots}, pasandole los dos vectores.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xd }\OperatorTok{=}\NormalTok{ [a}\OperatorTok{+}\FloatTok{1}\OperatorTok{/}\FloatTok{10}\NormalTok{i for i}\OperatorTok{=}\FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{]}
\FunctionTok{scatter}\NormalTok{(xd, }\FunctionTok{f}\NormalTok{.(xd), label}\OperatorTok{=}\StringTok{"Aproximación por la derecha"}\NormalTok{)}
\NormalTok{xi }\OperatorTok{=}\NormalTok{ [a}\OperatorTok{{-}}\FloatTok{1}\OperatorTok{/}\FloatTok{10}\NormalTok{i for i}\OperatorTok{=}\FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{]}
\FunctionTok{scatter!}\NormalTok{(xi, }\FunctionTok{f}\NormalTok{.(xi), label}\OperatorTok{=}\StringTok{"Aproximación por la izquierda"}\NormalTok{, legend}\OperatorTok{=:}\NormalTok{topleft)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./limites_files/figure-pdf/cell-5-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Calcular el límite por la izquierda y por la derecha de \(f\) en
  \(x=3\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Declarar la variable simbólica \texttt{x} con \texttt{@vars} imponiento
la restricción \texttt{real=true}, definir la función y usar la función
\href{https://docs.juliahub.com/SymPy/KzewI/1.0.31/Tutorial/calculus/\#Limits-1}{\texttt{limit}}
del paquete \texttt{SymPy} para calcular los límites laterales de la
función. Para el límite por la izquierda indicar el parámetro
\texttt{dir="-"} y para el límite por la derecha \texttt{dir="+"}.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\PreprocessorTok{@vars}\NormalTok{ x real}\OperatorTok{=}\ConstantTok{true}
\NormalTok{li }\OperatorTok{=} \FunctionTok{limit}\NormalTok{(}\FunctionTok{f}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{3}\NormalTok{, dir}\OperatorTok{=}\StringTok{"{-}"}\NormalTok{)}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite por la izquierda: "}\NormalTok{, li)}
\NormalTok{ld }\OperatorTok{=} \FunctionTok{limit}\NormalTok{(}\FunctionTok{f}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{3}\NormalTok{, dir}\OperatorTok{=}\StringTok{"+"}\NormalTok{)}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite por la derecha: "}\NormalTok{, ld)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Límite por la izquierda: 9
Límite por la derecha: 9
\end{verbatim}

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-tendencia-2}{}}%
\begin{exercise}[]\label{exr-tendencia-2}

Sea la función \(g(x)=(1+x)^{1/x}\).

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Estudiar la tendencia de \(g\) cuando \(x\) se aproxima a \(0\) por la
  derecha, evaluando la función en \(x=\frac{1}{10^i}\) para
  \(i=1,\ldots,10\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{g}\NormalTok{(x) }\OperatorTok{=}\NormalTok{ (}\FloatTok{1}\OperatorTok{+}\NormalTok{x)}\OperatorTok{\^{}}\NormalTok{(}\FloatTok{1}\OperatorTok{/}\NormalTok{x)}
\NormalTok{a }\OperatorTok{=} \FloatTok{0}
\FunctionTok{print}\NormalTok{([}\FunctionTok{g}\NormalTok{(a}\OperatorTok{+}\FloatTok{1}\OperatorTok{/}\FloatTok{10}\OperatorTok{\^{}}\NormalTok{i) for i }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[2.5937424601000023, 2.7048138294215285, 2.7169239322355936, 2.7181459268249255, 2.718268237192297, 2.7182804690957534, 2.7182816941320813, 2.7182817983473577, 2.71828205201156, 2.7182820532347876]
\end{verbatim}

La función tiende a \(e\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Estudiar la tendencia de \(g\) cuando \(x\) se aproxima a \(0\) por la
  izquierda, evaluando la función en \(x=-\frac{1}{10^i}\) para
  \(i=1,\ldots, 10\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{([}\FunctionTok{g}\NormalTok{(a}\OperatorTok{{-}}\FloatTok{1}\OperatorTok{/}\FloatTok{10}\OperatorTok{\^{}}\NormalTok{i) for i }\OperatorTok{=} \FloatTok{1}\OperatorTok{:}\FloatTok{10}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[2.867971990792441, 2.7319990264290284, 2.7196422164428524, 2.71841775501015, 2.718295419980405, 2.7182831876793716, 2.7182819629423656, 2.7182818557091664, 2.7182817529399266, 2.718282053506616]
\end{verbatim}

La función también tiende a e.

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Calcular el límite por la izquierda y por la derecha de \(g\) en
  \(x=0\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\PreprocessorTok{@vars}\NormalTok{ x real}\OperatorTok{=}\ConstantTok{true}
\NormalTok{li }\OperatorTok{=} \FunctionTok{limit}\NormalTok{(}\FunctionTok{g}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{0}\NormalTok{, dir}\OperatorTok{=}\StringTok{"{-}"}\NormalTok{)}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite por la izquierda: "}\NormalTok{, li)}
\NormalTok{ld }\OperatorTok{=} \FunctionTok{limit}\NormalTok{(}\FunctionTok{g}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{0}\NormalTok{, dir}\OperatorTok{=}\StringTok{"+"}\NormalTok{)}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite por la derecha: "}\NormalTok{, ld)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Límite por la izquierda: E
Límite por la derecha: E
\end{verbatim}

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-limites-laterales}{}}%
\begin{exercise}[]\label{exr-limites-laterales}

Considérese la función \[
f(x)=\left( 1+\frac{2}{x}\right) ^{x/2}.
\]

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\item
  Dibujar su gráfica, y a la vista de misma conjeturar el resultado de
  los siguientes límites:
\item
  \(\lim_{x\rightarrow -2^-} f(x)\)
\item
  \(\lim_{x\rightarrow -2^+} f(x)\)
\item
  \(\lim_{x\rightarrow -\infty} f(x)\)
\item
  \(\lim_{x\rightarrow +\infty} f(x)\)
\item
  \(\lim_{x\rightarrow 2} f(x)\)
\item
  \(\lim_{x\rightarrow 0} f(x)\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Utilizar la función
\href{https://aprendeconalf.es/manual-julia/graficos.html\#gr\%C3\%A1fica-de-una-funci\%C3\%B3n-de-una-variable}{\texttt{plot!}}
del paquete \texttt{Plots}. Usar los parámetros \texttt{xlims=(a,b)}
para restringir la región de dibujo al intervalo \((a,b)\) del eje
\(x\), y \texttt{ylims=(c,d)} para restringir la región de dibujo al
intervalo \((c,d)\) del eje \(y\).

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{f}\NormalTok{(x) }\OperatorTok{=}\NormalTok{ (}\FloatTok{1}\OperatorTok{+}\FloatTok{2}\OperatorTok{/}\NormalTok{x)}\OperatorTok{\^{}}\NormalTok{(x}\OperatorTok{/}\FloatTok{2}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(f, xlims}\OperatorTok{=}\NormalTok{(}\OperatorTok{{-}}\FloatTok{10}\NormalTok{,}\FloatTok{10}\NormalTok{), ylims}\OperatorTok{=}\NormalTok{(}\FloatTok{0}\NormalTok{,}\FloatTok{6}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./limites_files/figure-pdf/cell-10-output-1.pdf}

}

\end{figure}

A la vista de la gráfica, se puede concluir que

\begin{enumerate}
\def\labelenumi{\roman{enumi}.}
\tightlist
\item
  \(\lim_{x\rightarrow -2^-} f(x) = -\infty.\)
\item
  \(\lim_{x\rightarrow -2^+} f(x)\) no existe.
\item
  \(\lim_{x\rightarrow -\infty} f(x)\approx 2.7.\)
\item
  \(\lim_{x\rightarrow +\infty} f(x) \approx 2.7.\)
\item
  \(\lim_{x\rightarrow 2} f(x) = 2.\)
\item
  \(\lim_{x\rightarrow 0} f(x)\) no existe.
\end{enumerate}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Calcular los límites anteriores. ¿Coinciden los resultados con los
  conjeturados?
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{SymPy}
\PreprocessorTok{@vars}\NormalTok{ x real}\OperatorTok{=}\ConstantTok{true}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite por la izquieda en {-}2: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{f}\NormalTok{(x), x}\OperatorTok{=\textgreater{}{-}}\FloatTok{2}\NormalTok{, dir}\OperatorTok{=}\StringTok{"{-}"}\NormalTok{))}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite por la izquieda en {-}2: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{f}\NormalTok{(x), x}\OperatorTok{=\textgreater{}{-}}\FloatTok{2}\NormalTok{, dir}\OperatorTok{=}\StringTok{"+"}\NormalTok{))}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite en {-}∞: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{f}\NormalTok{(x), x}\OperatorTok{=\textgreater{}{-}}\NormalTok{oo))}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite en ∞: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{f}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\NormalTok{oo))}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite en 2: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{f}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{2}\NormalTok{))}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite en 0: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{f}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{0}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Límite por la izquieda en -2: oo
Límite por la izquieda en -2: 
\end{verbatim}

\begin{verbatim}
-oo
Límite en -∞: E
Límite en ∞: E
Límite en 2: 2
Límite en 0: 
\end{verbatim}

\begin{verbatim}
1
\end{verbatim}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-caution-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-caution-color}{\faFire}\hspace{0.5em}{Precaución}, colframe=quarto-callout-caution-color-frame, toprule=.15mm]

Aunque Julia calcula el límite en \(-2\) por la derecha y el límite en
\(0\), a la vista de la gráfica, estos límites en realidad no existen,
ya que la función no está definida en el intervalo de \([-2,0]\).

\end{tcolorbox}

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-limites-raros}{}}%
\begin{exercise}[]\label{exr-limites-raros}

Calcular los siguientes límites

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  \(\lim_{x\to 0} \operatorname{sen}\left(\frac{1}{x}\right)\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{SymPy}
\PreprocessorTok{@vars}\NormalTok{ x real}\OperatorTok{=}\ConstantTok{true}
\FunctionTok{limit}\NormalTok{(}\FunctionTok{sin}\NormalTok{(}\FloatTok{1}\OperatorTok{/}\NormalTok{x), x}\OperatorTok{=\textgreater{}}\FloatTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

$\left\langle -1, 1\right\rangle$

Como no se obtiene un valor concreto, sino un rango de valores, el
límite no existe.

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \(\lim_{x\to 0} x\operatorname{sen}\left(\frac{1}{x}\right)\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{limit}\NormalTok{(}\FunctionTok{x*sin}\NormalTok{(}\FloatTok{1}\OperatorTok{/}\NormalTok{x), x}\OperatorTok{=\textgreater{}}\FloatTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

$0$

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \(\lim_{x\to \infty} e^{-x}\operatorname{sen}(x)\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{limit}\NormalTok{(}\ConstantTok{ℯ}\OperatorTok{\^{}}\NormalTok{(}\OperatorTok{{-}}\NormalTok{x)}\FunctionTok{*sin}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\NormalTok{oo)}
\end{Highlighting}
\end{Shaded}

$0$

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \(\lim_{x\to a} \frac{\operatorname{sen}(x)-\operatorname{sen}(a)}{x-a}\)
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\PreprocessorTok{@vars}\NormalTok{ a real}\OperatorTok{=}\ConstantTok{true}
\FunctionTok{limit}\NormalTok{((}\FunctionTok{sin}\NormalTok{(x)}\FunctionTok{{-}sin}\NormalTok{(a))}\OperatorTok{/}\NormalTok{(x}\OperatorTok{{-}}\NormalTok{a), x}\OperatorTok{=\textgreater{}}\NormalTok{a)}
\end{Highlighting}
\end{Shaded}

$\cos{\left(a \right)}$

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-indeterminaciones}{}}%
\begin{exercise}[]\label{exr-indeterminaciones}

Calcular el valor de las siguientes funciones en los puntos dados y su
límite. Corroborar los límites obtenidos gráficamente.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  \(f(x)=\frac{\operatorname{sen}(x)}{x}\) en \(x=0\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

La función \(f\) no está definida en \(x=0\) de manera que al evaluarla
en \(0\) obtenemos un valor indeterminado.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{f}\NormalTok{(x)}\OperatorTok{=}\FunctionTok{sin}\NormalTok{(x)}\OperatorTok{/}\NormalTok{x}
\FunctionTok{f}\NormalTok{(}\FloatTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
NaN
\end{verbatim}

Ahora calculamos el límite de \(f\) en \(0\).

\begin{Shaded}
\begin{Highlighting}[]
\PreprocessorTok{@vars}\NormalTok{ x real}\OperatorTok{=}\ConstantTok{true}
\FunctionTok{f}\NormalTok{(x)}\OperatorTok{=}\FunctionTok{sin}\NormalTok{(x)}\OperatorTok{/}\NormalTok{x}
\FunctionTok{limit}\NormalTok{(}\FunctionTok{f}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

$1$

Para corroborar el límite dibujamos la gráfica de \(f\) en un entorno de
\(0\).

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{plot}\NormalTok{(f)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./limites_files/figure-pdf/cell-18-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \(g(x)=\frac{\cos(x)}{x-\pi/2}\) en \(x=\pi/2\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

La función \(f\) no está definida en \(x=0\) de manera que al evaluarla
en \(0\) obtenemos un valor indeterminado.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{g}\NormalTok{(x)}\OperatorTok{=}\FunctionTok{cos}\NormalTok{(x)}\OperatorTok{/}\NormalTok{(x}\OperatorTok{{-}}\ConstantTok{pi}\OperatorTok{/}\FloatTok{2}\NormalTok{)}
\FunctionTok{g}\NormalTok{(}\ConstantTok{pi}\OperatorTok{/}\FloatTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Inf
\end{verbatim}

Como se puede observar, se obtiene \(\infty\) en lugar de indeterminado.
La razón está en la representación de los números reales mediante
números con coma flotante, de manera que \(\pi/2\) se redondea al número
de coma flotante más próximo, y al aplicar el coseno se obtiene un
número muy próximo a \(0\) pero distinto de \(0\).

Ahora calculamos el límite de \(g\) en \(\pi/2\).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{limit}\NormalTok{(}\FunctionTok{g}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\ConstantTok{pi}\OperatorTok{/}\FloatTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

$\infty$

Para corroborar el límite dibujamos la gráfica de \(g\) en un entorno de
\(\pi/2\).

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}
\FunctionTok{plot}\NormalTok{(g)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./limites_files/figure-pdf/cell-21-output-1.pdf}

}

\end{figure}

Como se puede apreciar gráficamente el la tendencia de \(g\) en
\(\pi/2\) es \(-1\) y no el valor obtenido con el cálculo del límite. De
nuevo el problema está en la aproximación de \(pi\) como un real en coma
flotante. Afortunadamente el paquete \texttt{SymPy} permite definir una
constante como simbólica para evitar su conversión a número en coma
flotante, usando la función \texttt{Sym()}. Repetimos la definición de
la función y el cálculo de nuevo convirtiendo \(\pi\) en una constante
simbólica.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{g}\NormalTok{(x)}\OperatorTok{=}\FunctionTok{cos}\NormalTok{(x)}\OperatorTok{/}\NormalTok{(}\FunctionTok{x{-}Sym}\NormalTok{(}\ConstantTok{pi}\NormalTok{)}\OperatorTok{/}\FloatTok{2}\NormalTok{)}
\FunctionTok{limit}\NormalTok{(}\FunctionTok{g}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FunctionTok{Sym}\NormalTok{(}\ConstantTok{pi}\NormalTok{)}\OperatorTok{/}\FloatTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

$-1$

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-asintotas}{}}%
\begin{exercise}[]\label{exr-asintotas}

Considérese la función \[
g(x)=
\begin{cases}
\dfrac{x}{x-2}    & \mbox{si $x\leq 0$;} \\
\dfrac{x^2}{2x-6} & \mbox{si $x>0$;}
\end{cases}
\]

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Dibujar la gráfica de \(g\) y determinar gráficamente si existen
  asíntotas.
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Para respetar las discontinuidades utilizar la función
\texttt{rangeclamp()} del paquete \texttt{MTH229}.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}\NormalTok{, }\BuiltInTok{MTH229}\NormalTok{, }\BuiltInTok{LaTeXStrings}
\PreprocessorTok{@vars}\NormalTok{ x real}\OperatorTok{=}\ConstantTok{true}
\FunctionTok{g1}\NormalTok{(x) }\OperatorTok{=}\NormalTok{ x}\OperatorTok{/}\NormalTok{(x}\OperatorTok{{-}}\FloatTok{2}\NormalTok{)}
\FunctionTok{g2}\NormalTok{(x) }\OperatorTok{=}\NormalTok{ x}\OperatorTok{\^{}}\FloatTok{2}\OperatorTok{/}\NormalTok{(}\FloatTok{2}\NormalTok{x}\OperatorTok{{-}}\FloatTok{6}\NormalTok{)}
\FunctionTok{g}\NormalTok{(x) }\OperatorTok{=}\NormalTok{ x}\OperatorTok{\textless{}=}\FloatTok{0}\NormalTok{ ? }\FunctionTok{g1}\NormalTok{(x) }\OperatorTok{:} \FunctionTok{g2}\NormalTok{(x)}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{rangeclamp}\NormalTok{(g), xlims}\OperatorTok{=}\NormalTok{(}\OperatorTok{{-}}\FloatTok{5}\NormalTok{,}\FloatTok{10}\NormalTok{), ylims}\OperatorTok{=}\NormalTok{(}\OperatorTok{{-}}\FloatTok{5}\NormalTok{,}\FloatTok{10}\NormalTok{), xticks}\OperatorTok{={-}}\FloatTok{5}\OperatorTok{:}\FloatTok{10}\NormalTok{, label }\OperatorTok{=}\NormalTok{ L}\StringTok{"g(x)"}\NormalTok{, legend}\OperatorTok{=:}\NormalTok{topleft)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./limites_files/figure-pdf/cell-23-output-1.pdf}

}

\end{figure}

A la vista de la gráfica, se observa que \(g\) tiene una asíntota
vertical en \(x=3\), una asíntota horizontal \(y=1\) en \(-\infty\) y
parece que también hay una asíntota oblicua en \(\infty\).

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Calcular las asíntotas verticales de \(g\) y dibujarlas.
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Estudiamos primero el dominio para ver dónde no está definida la
función. Como tanto la rama negativa como la positiva son funciones
racionales, hay que ver los puntos que anulan el denominador.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{println}\NormalTok{(}\StringTok{"Puntos fuera del dominio de la rama negativa: "}\NormalTok{, }\FunctionTok{solve}\NormalTok{(x}\OperatorTok{{-}}\FloatTok{2}\NormalTok{))}
\FunctionTok{println}\NormalTok{(}\StringTok{"Puntos fuera del dominio de la rama positiva: "}\NormalTok{, }\FunctionTok{solve}\NormalTok{(}\FloatTok{2}\NormalTok{x}\OperatorTok{{-}}\FloatTok{6}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Puntos fuera del dominio de la rama negativa: Sym[2]
Puntos fuera del dominio de la rama positiva: Sym[3]
\end{verbatim}

Así pues la rama negativa está definida en todos \(\mathbb{R}^-\) y la
rama positiva en \(\mathbb{R}^+\setminus\{3\}\). Es en este último punto
donde \(g\) puede tener asíntota vertical, así que estudiamos los
límites laterales.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{println}\NormalTok{(}\StringTok{"Límte en 3 por la izquierda: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{g}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{3}\NormalTok{, dir}\OperatorTok{=}\StringTok{"{-}"}\NormalTok{))}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límte en 3 por la derecha: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{g}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{3}\NormalTok{, dir}\OperatorTok{=}\StringTok{"+"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Límte en 3 por la izquierda: -oo
Límte en 3 por la derecha: oo
\end{verbatim}

Por tanto, \(g\) tiene una asíntota vertical en \(x=3\).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{vline!}\NormalTok{([}\FloatTok{3}\NormalTok{], label }\OperatorTok{=}\NormalTok{ L}\StringTok{"Asíntota vertical }\SpecialCharTok{$}\NormalTok{x}\StringTok{=3}\SpecialCharTok{$}\StringTok{")}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./limites_files/figure-pdf/cell-26-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Calcular las asíntotas horizontales de \(g\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Estudiamos los límites en el infinito.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite en {-}∞: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{g1}\NormalTok{(x), x}\OperatorTok{=\textgreater{}{-}}\NormalTok{oo))}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite en ∞: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{g2}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\NormalTok{oo))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Límite en -∞: 1
Límite en ∞: oo
\end{verbatim}

Por tanto, \(g\) tiene una asíntota horizontal \(y=1\) en \(-\infty\).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hline!}\NormalTok{([}\FloatTok{1}\NormalTok{], label }\OperatorTok{=}\NormalTok{ L}\StringTok{"Asíntota horizontal }\SpecialCharTok{$}\NormalTok{y}\StringTok{=1}\SpecialCharTok{$}\StringTok{")}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./limites_files/figure-pdf/cell-28-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Calcular las asíntotas oblicuas de \(g\).
\end{enumerate}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Estudiamos el límite en \(\infty\) de \(\frac{f(x)}{x}\) (en \(-\infty\)
no puede haber asíntota oblicua al haber asíntota horizontal).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{limit}\NormalTok{(}\FunctionTok{g2}\NormalTok{(x)}\OperatorTok{/}\NormalTok{x, x}\OperatorTok{=\textgreater{}}\NormalTok{oo)}
\end{Highlighting}
\end{Shaded}

$\frac{1}{2}$

Por tanto, \(g\) tiene una asíntota oblicua con pendiente \(b=1/2\) en
\(\infty\). Para obtener el término independiente de la asíntota
calculamos el límite en \(\infty\) de \(f(x)-\frac{1}{2}x\).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{limit}\NormalTok{(}\FunctionTok{g2}\NormalTok{(x)}\OperatorTok{{-}}\NormalTok{x}\OperatorTok{/}\FloatTok{2}\NormalTok{, x}\OperatorTok{=\textgreater{}}\NormalTok{oo)}
\end{Highlighting}
\end{Shaded}

$\frac{3}{2}$

Por tanto, \(g\) tiene una asíntota oblicua
\(y=\frac{3}{2}+\frac{1}{2}x\).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot!}\NormalTok{(}\FloatTok{3}\OperatorTok{/}\FloatTok{2}\OperatorTok{+}\NormalTok{x}\OperatorTok{/}\FloatTok{2}\NormalTok{, label }\OperatorTok{=}\NormalTok{ L}\StringTok{"Asíntota oblicua }\SpecialCharTok{$}\NormalTok{y}\StringTok{=}\SpecialCharTok{\textbackslash{}f}\StringTok{rac\{3\}\{2\}+}\SpecialCharTok{\textbackslash{}f}\StringTok{rac\{1\}\{2\}x}\SpecialCharTok{$}\StringTok{")}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./limites_files/figure-pdf/cell-31-output-1.pdf}

}

\end{figure}

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-continuidad}{}}%
\begin{exercise}[]\label{exr-continuidad}

Dada la función

\[
h(x)=
\begin{cases}
\frac{2x^2-2x}{3x^2+x} & \mbox{si } x\leq 0,\\
\frac{\operatorname{tg}(x)+a}{x} & \mbox{si } x>0
\end{cases}
\]

¿Qué valor debe tomar \(a\) para que la función sea continua en todo su
dominio?

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Ayuda}, colframe=quarto-callout-note-color-frame, toprule=.15mm]

Calcular el límite en \(0\) por la izquierda de la función de la rama
negativa, y el límite en \(0\) por la derecha de la función de la rama
positiva. Después resolver la ecuación simbólica que resulta de igualar
los dos límites. Para crear la ecuación simbólica debe utilizarse la
función \texttt{Eq()} del paquete \texttt{SymPy} y después resolverla
con la función \texttt{solve()}.

\end{tcolorbox}

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\PreprocessorTok{@vars}\NormalTok{ x a real}\OperatorTok{=}\ConstantTok{true}
\FunctionTok{h1}\NormalTok{(x) }\OperatorTok{=}\NormalTok{ (}\FloatTok{2}\NormalTok{x}\OperatorTok{\^{}}\FloatTok{2}\OperatorTok{{-}}\FloatTok{2}\NormalTok{x)}\OperatorTok{/}\NormalTok{(}\FloatTok{3}\NormalTok{x}\OperatorTok{\^{}}\FloatTok{2}\OperatorTok{+}\NormalTok{x)}
\FunctionTok{h2}\NormalTok{(x) }\OperatorTok{=}\NormalTok{ (}\FunctionTok{tan}\NormalTok{(x)}\OperatorTok{{-}}\NormalTok{a}\OperatorTok{*}\NormalTok{x)}\OperatorTok{/}\NormalTok{x }
\NormalTok{l1 }\OperatorTok{=} \FunctionTok{limit}\NormalTok{(}\FunctionTok{h1}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{0}\NormalTok{, dir}\OperatorTok{=}\StringTok{"{-}"}\NormalTok{)}
\NormalTok{l2 }\OperatorTok{=} \FunctionTok{limit}\NormalTok{(}\FunctionTok{h2}\NormalTok{(x),x}\OperatorTok{=\textgreater{}}\FloatTok{0}\NormalTok{, dir}\OperatorTok{=}\StringTok{"+"}\NormalTok{)}
\FunctionTok{solve}\NormalTok{(}\FunctionTok{Eq}\NormalTok{(l1,l2))}
\end{Highlighting}
\end{Shaded}

$\left[ \begin{array}{r}3\end{array} \right]$

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-discontinuidad}{}}%
\begin{exercise}[]\label{exr-discontinuidad}

Representar gráficamente y clasificar las discontinuidades de la función

\[
f(x)=
\begin{cases}
\frac{x+1}{x^2-1},       & \mbox{si } x<0,     \\
\frac{1}{e^{1/(x^2-1)}}, & \mbox{si } x\geq 0. 
\end{cases}
\]

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

Para estudiar las discontinuidades de una función tenemos que estudiar
los puntos que no están en el dominio y los puntos donde cambia la
definición de la función en el caso de una función definida a trozos.

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{using} \BuiltInTok{Plots}\NormalTok{, }\BuiltInTok{MTH229}\NormalTok{, }\BuiltInTok{LaTeXStrings}
\PreprocessorTok{@syms}\NormalTok{ x}\OperatorTok{::}\DataTypeTok{real}
\FunctionTok{f1}\NormalTok{(x) }\OperatorTok{=}\NormalTok{ (x}\OperatorTok{+}\FloatTok{1}\NormalTok{)}\OperatorTok{/}\NormalTok{(x}\OperatorTok{\^{}}\FloatTok{2}\OperatorTok{{-}}\FloatTok{1}\NormalTok{)}
\FunctionTok{f2}\NormalTok{(x) }\OperatorTok{=} \FloatTok{1}\OperatorTok{/}\FunctionTok{exp}\NormalTok{(}\FloatTok{1}\OperatorTok{/}\NormalTok{(x}\OperatorTok{\^{}}\FloatTok{2}\OperatorTok{{-}}\FloatTok{1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(f1, }\OperatorTok{{-}}\FloatTok{4}\NormalTok{, }\FloatTok{0}\NormalTok{, ylim}\OperatorTok{=}\NormalTok{(}\OperatorTok{{-}}\FloatTok{2}\NormalTok{,}\FloatTok{8}\NormalTok{), legend}\OperatorTok{=}\ConstantTok{false}\NormalTok{)}
\FunctionTok{plot!}\NormalTok{(}\FunctionTok{rangeclamp}\NormalTok{(f2), }\FloatTok{0}\NormalTok{, }\FloatTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{./limites_files/figure-pdf/cell-33-output-1.pdf}

}

\end{figure}

Para determinar el dominio de la rama negativa, al ser una función
racional, tenemos que ver los puntos que anulan el denominador.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{solve}\NormalTok{(x}\OperatorTok{\^{}}\FloatTok{2}\OperatorTok{{-}}\FloatTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

$\left[ \begin{array}{r}-1\\1\end{array} \right]$

Así pues, la función no está definida en \(x=-1\) (la otra raíz queda
fuera de la rama negativa). Para ver el tipo de discontinuidad
estudiamos los límites laterales en \(x=-1\).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite en {-}1 por la izquierda: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{f1}\NormalTok{(x), x}\OperatorTok{=\textgreater{}} \OperatorTok{{-}}\FloatTok{1}\NormalTok{, dir}\OperatorTok{=}\StringTok{"{-}"}\NormalTok{))}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite en {-}1 por la derecha: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{f1}\NormalTok{(x), x}\OperatorTok{=\textgreater{}} \OperatorTok{{-}}\FloatTok{1}\NormalTok{, dir}\OperatorTok{=}\StringTok{"+"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Límite en -1 por la izquierda: -1/2
Límite en -1 por la derecha: 
\end{verbatim}

\begin{verbatim}
-1/2
\end{verbatim}

Como el límite existe, \(f\) tiene una discontinuidad evitable en
\(x=-1\).

Del mismo modo la rama positiva no está definida en \(x=1\) ya que se
anula el denominador del exponente de la función exponencial. Para ver
el tipo de discontinuidad estudiamos los límites laterales en \(x=1\).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite en 1 por la izquierda: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{f2}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{1}\NormalTok{, dir}\OperatorTok{=}\StringTok{"{-}"}\NormalTok{))}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite en 1 por la derecha: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{f2}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{1}\NormalTok{, dir}\OperatorTok{=}\StringTok{"+"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Límite en 1 por la izquierda: oo
Límite en 1 por la derecha: 
\end{verbatim}

\begin{verbatim}
0
\end{verbatim}

Como los límites laterales son distintos, \(f\) tiene una discontinuidad
de salto infinito en \(x=1\).

Finalmente, estudiamos los límites laterales en \(x=0\), que es donde
cambia la definición de la función.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite en 1 por la izquierda: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{f1}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{0}\NormalTok{, dir}\OperatorTok{=}\StringTok{"{-}"}\NormalTok{))}
\FunctionTok{println}\NormalTok{(}\StringTok{"Límite en 1 por la derecha: "}\NormalTok{, }\FunctionTok{limit}\NormalTok{(}\FunctionTok{f2}\NormalTok{(x), x}\OperatorTok{=\textgreater{}}\FloatTok{0}\NormalTok{, dir}\OperatorTok{=}\StringTok{"+"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Límite en 1 por la izquierda: -1
Límite en 1 por la derecha: E
\end{verbatim}

Como los límites laterales son distintos, \(f\) tiene una discontinuidad
de salto finito en \(x=0\).

\end{tcolorbox}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-algoritmo-biseccion}{}}%
\begin{exercise}[]\label{exr-algoritmo-biseccion}

El
\href{https://aprendeconalf.es/analisis-manual/limites.html\#thm-bolzano}{teorema
de Bolzano} permite construir un algoritmo para encontrar raíces de una
función continua en un intervalo \([a,b]\) cuando \(f(a)f(b)<0\). Este
algoritmo se conoce como el \emph{algoritmo de bisección} y básicamente
consiste en repetir los siguientes pasos:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Calcular el centro del intervalo \(c=\frac{a+b}{2}\).
\item
  Si \(f(c)=0\), \(c\) es una raíz y se termina la búsqueda.
\item
  En caso contrario, si \(f(a)f(c)<0\) hacer \(b=c\), y si no, hacer
  \(a=c\).
\item
  Repetir la búsqueda.
\end{enumerate}

Construir una función que implemente este algoritmo y utilizarlo para
calcular una raíz de la función \(f(x)=x^5+3x^4-2x^3+6x-2\) en el
intervalo \([0,1]\).

\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, rightrule=.15mm, arc=.35mm, colbacktitle=quarto-callout-tip-color!10!white, colback=white, breakable, left=2mm, bottomrule=.15mm, coltitle=black, opacitybacktitle=0.6, opacityback=0, bottomtitle=1mm, toptitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Solución}, colframe=quarto-callout-tip-color-frame, toprule=.15mm]

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{function} \FunctionTok{raices\_biseccion}\NormalTok{(f, a, b, error}\OperatorTok{=}\FloatTok{1e{-}10}\NormalTok{)}
  \ControlFlowTok{if} \FunctionTok{f}\NormalTok{(a) }\OperatorTok{==} \FloatTok{0} \ControlFlowTok{return}\NormalTok{(a) }\ControlFlowTok{end}
  \ControlFlowTok{if} \FunctionTok{f}\NormalTok{(b) }\OperatorTok{==} \FloatTok{0} \ControlFlowTok{return}\NormalTok{(b) }\ControlFlowTok{end}
  \ControlFlowTok{if} \FunctionTok{f}\NormalTok{(a) }\OperatorTok{*} \FunctionTok{f}\NormalTok{(b) }\OperatorTok{\textgreater{}} \FloatTok{0} \FunctionTok{error}\NormalTok{(}\StringTok{"Las imágenes de los extremos del intervalo no tienen signo distinto."}\NormalTok{) }\ControlFlowTok{end}
\NormalTok{  c }\OperatorTok{=}\NormalTok{ (a}\OperatorTok{+}\NormalTok{b)}\OperatorTok{/}\FloatTok{2}
  \ControlFlowTok{while} \FunctionTok{abs}\NormalTok{(b}\OperatorTok{{-}}\NormalTok{a) }\OperatorTok{\textgreater{}}\NormalTok{ error}
    \ControlFlowTok{if} \FunctionTok{f}\NormalTok{(c) }\OperatorTok{==} \FloatTok{0} \ControlFlowTok{return}\NormalTok{(c) }\ControlFlowTok{end}
    \ControlFlowTok{if} \FunctionTok{f}\NormalTok{(a) }\OperatorTok{*} \FunctionTok{f}\NormalTok{(c) }\OperatorTok{\textless{}} \FloatTok{0}
\NormalTok{       b }\OperatorTok{=}\NormalTok{ c}
    \ControlFlowTok{else}
\NormalTok{       a }\OperatorTok{=}\NormalTok{ c}
    \ControlFlowTok{end}
\NormalTok{    c }\OperatorTok{=}\NormalTok{ (a}\OperatorTok{+}\NormalTok{b)}\OperatorTok{/}\FloatTok{2}
  \ControlFlowTok{end}
\NormalTok{  c}
\KeywordTok{end}

\FunctionTok{f}\NormalTok{(x)}\OperatorTok{=}\NormalTok{x}\OperatorTok{\^{}}\FloatTok{5}\OperatorTok{+}\FloatTok{3}\NormalTok{x}\OperatorTok{\^{}}\FloatTok{4}\OperatorTok{{-}}\FloatTok{2}\NormalTok{x}\OperatorTok{\^{}}\FloatTok{3}\OperatorTok{+}\FloatTok{6}\NormalTok{x}\OperatorTok{{-}}\FloatTok{4}
\FunctionTok{print}\NormalTok{(}\FunctionTok{raices\_biseccion}\NormalTok{(f, }\FloatTok{0}\NormalTok{, }\FloatTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
0.6496996753558051
\end{verbatim}

\end{tcolorbox}

\end{exercise}

\hypertarget{ejercicios-propuestos-2}{%
\section{Ejercicios propuestos}\label{ejercicios-propuestos-2}}

\leavevmode\vadjust pre{\hypertarget{exr-interes-compuesto}{}}%
\begin{exercise}[]\label{exr-interes-compuesto}

En 1683 Jacob Bernouilli estudió la evolución del interés compuesto
cuando el periodo de actualización se hacía cada vez más pequeño.

Si disponemos de \(1\)€ en una cuenta corriente que ofrece un 100\% de
interés anual, al cabo de un año tendremos \(2\)€ en la cuenta. Si la
cuenta ofrece un interés del \(50\)\% cada 6 meses, al final del año
tendremos

\[
1\cdot\left(1+\frac{1}{2}\right)\left(1+\frac{1}{2}\right)= \left(1+\frac{1}{2}\right)^2 = 2.25\mbox{€}.
\]

Si la cuenta ofrece un interés del \(25\)\% cada trimestre, al final del
año tendremos

\[
1\cdot\left(1+\frac{1}{4}\right)\left(1+\frac{1}{4}\right)\left(1+\frac{1}{4}\right)\left(1+\frac{1}{4}\right)= \left(1+\frac{1}{4}\right)^4 = 2.44140625\mbox{€}.
\]

¿Qué cantidad habrá en la cuenta al cabo de un año si la cuenta ofrece
un interés del \(1/12\)\% mensual?

\vspace{18pt}*Hint: *

Introducir hasta 10 decimales

¿Qué cantidad habrá en la cuenta al cabo de un año si la cuenta ofrece
un interés del \(1/365\)\% diario?

\vspace{18pt}*Hint: *

Introducir hasta 10 decimales

¿Qué cantidad habrá en la cuenta al cabo de un año si la cuenta se
actualiza de manera continua con un interés \(1/x\)\% cuando
\(x\to\infty\)?

${\quad\Box}$ 3

${\quad\Box}$ $$e^2$$
${\quad\Box}$ 2.7182818284590

${\quad\Box}$ $$e^{-1}$$
${\quad\Box}$ e

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-limites-2}{}}%
\begin{exercise}[]\label{exr-limites-2}

Calcular los siguientes límites.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  \(\displaystyle \lim_{x\rightarrow \pi/4}\frac{\operatorname{sen}(x)-\cos(x)}{1-\operatorname{tg}(x)}\).
\end{enumerate}

\vspace{18pt}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \(\displaystyle \lim_{x\rightarrow \infty}\sqrt{x^2+x+1}-\sqrt{x^2-2x-1}\).
\end{enumerate}

\vspace{18pt}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \(\displaystyle \lim_{x\to 0^+} \frac{x^x-1}{x}\)
\end{enumerate}

${\quad\Box}$ $$\infty$$
${\quad\Box}$ $$-\infty$$
${\quad\Box}$ $$1$$
${\quad\Box}$ 0

${\quad\Box}$ NaN

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  \(\displaystyle \lim_{x\to 1}\frac{a^{1-x}-1}{1-x}\).
\end{enumerate}

${\quad\Box}$ $$1/a$$
${\quad\Box}$ $$\ln(a)$$
${\quad\Box}$ $$e^a$$
${\quad\Box}$ $$\sqrt{a}$$
${\quad\Box}$ Las otras opciones son falsas.

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-asintotas}{}}%
\begin{exercise}[]\label{exr-asintotas}

¿Cuáles de las siguientes rectas son asíntotas de la función
\(f(x)=\frac{x^2+1}{3x+3}\)?

${\quad\Box}$ $$y=\frac{1}{3}+\frac{1}{3}x$$
${\quad\Box}$ $$y=3x+1$$
${\quad\Box}$ $$y=\frac{x-1}{3}$$
${\quad\Box}$ $$y=1$$
${\quad\Box}$ $$x=-1$$
(\emph{Select one or more})

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-discontinuidad-evitable}{}}%
\begin{exercise}[]\label{exr-discontinuidad-evitable}

¿Cuándo debería valer la función \(h(x)=\dfrac{e^x-e^{-x}}{x}\) para que
fuese continua en \(x=0\).

\vspace{18pt}

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-continuidad-2}{}}%
\begin{exercise}[]\label{exr-continuidad-2}

Dada la función

\[
h(x)=
\begin{cases}
x^3-x-2 & \mbox{si } x\leq 0,\\
\cos(x-\pi/2)+a & \mbox{si } x>0
\end{cases}
\]

¿Qué valor debe tomar \(a\) para que la función sea continua en todo su
dominio?

${\quad\Box}$ $$-2 - \frac{\sqrt{2}}{2}$$
${\quad\Box}$ $$-2+\frac{\sqrt{2}}{2}$$
${\quad\Box}$ $$2-\sqrt{2}$$
${\quad\Box}$ $$-2$$
${\quad\Box}$ No hay ningún valor de de $a$ que haga la función continua

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-clasificacion-discontinuidad}{}}%
\begin{exercise}[]\label{exr-clasificacion-discontinuidad}

¿Qué tipo de discontinuidad presenta la función
\(g(x)=\dfrac{1}{e^{1/(x^2-1)}}\) en \(x=-1\)?

${\quad\Box}$ Salto infinito

${\quad\Box}$ Salto finito

${\quad\Box}$ Es continua

${\quad\Box}$ Evitable

${\quad\Box}$ Segunda especie

\end{exercise}

\leavevmode\vadjust pre{\hypertarget{exr-raices}{}}%
\begin{exercise}[]\label{exr-raices}

Calcular de forma aproximada con el algoritmo de bisección una solución
de la ecuación \(e^{-x}=\cos(x)\) en el intervalo \([1,2]\) con un error
menor de \(10^{-15}\).

\vspace{18pt}

\end{exercise}



\end{document}
